<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; September 4, 2026 – SSBMF Progress Notebook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/2026-08-27.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f41698b1751ec46a43d81475a221ecf5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/2026-09-04.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">September 4, 2026</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SSBMF Progress Notebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this notebook</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-04-29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">April 29, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">May 7, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-28.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">May 28, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-07-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">July 15, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">August 3, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">August 21, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-27.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">August 27, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-09-04.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">September 4, 2026</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#clarifying-the-827-results" id="toc-clarifying-the-827-results" class="nav-link" data-scroll-target="#clarifying-the-827-results"><span class="header-section-number">8.1</span> §1 — Clarifying the 8/27 results</a></li>
  <li><a href="#are-retained-factors-sensitive-to-threshold-variation" id="toc-are-retained-factors-sensitive-to-threshold-variation" class="nav-link" data-scroll-target="#are-retained-factors-sensitive-to-threshold-variation"><span class="header-section-number">8.2</span> §2 — Are retained factors sensitive to threshold variation?</a></li>
  <li><a href="#cohort-membership-in-the-survival-term-performance-and-interpretability" id="toc-cohort-membership-in-the-survival-term-performance-and-interpretability" class="nav-link" data-scroll-target="#cohort-membership-in-the-survival-term-performance-and-interpretability"><span class="header-section-number">8.3</span> §3 — Cohort membership in the survival term: performance and interpretability</a>
  <ul class="collapse">
  <li><a href="#performance-statistically-indistinguishable-from-the-current-model" id="toc-performance-statistically-indistinguishable-from-the-current-model" class="nav-link" data-scroll-target="#performance-statistically-indistinguishable-from-the-current-model"><span class="header-section-number">8.3.1</span> Performance: statistically indistinguishable from the current model</a></li>
  <li><a href="#interpretability-seeing-how-cohorts-differ" id="toc-interpretability-seeing-how-cohorts-differ" class="nav-link" data-scroll-target="#interpretability-seeing-how-cohorts-differ"><span class="header-section-number">8.3.2</span> Interpretability: seeing how cohorts differ</a></li>
  <li><a href="#three-supporting-technical-notes" id="toc-three-supporting-technical-notes" class="nav-link" data-scroll-target="#three-supporting-technical-notes"><span class="header-section-number">8.3.3</span> Three supporting technical notes</a></li>
  </ul></li>
  <li><a href="#other-findings" id="toc-other-findings" class="nav-link" data-scroll-target="#other-findings"><span class="header-section-number">8.4</span> §4 — Other findings</a></li>
  <li><a href="#where-the-value-add-goes-next" id="toc-where-the-value-add-goes-next" class="nav-link" data-scroll-target="#where-the-value-add-goes-next"><span class="header-section-number">8.5</span> §5 — Where the value-add goes next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">September 4, 2026</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><strong>Cohort-specific survival coefficients (<code>beta_cohort_id</code>): no significant performance difference from the current model was detected, and the value-add is understanding how each cohort contributes to the learned factors</strong> — confirmed on real data and with simulated ground truth. (§3)</li>
<li><strong>Retained factors are not sensitive to the choice of retention threshold</strong> — the same 2 survival-active factors are kept across a 100x range of <code>beta_thresh</code> and every <code>pve_thresh</code> tested. (§2)</li>
<li><strong>The 8/27 log-likelihood and BIC were in-sample, not cross-validated.</strong> Now have genuine held-out versions alongside them; found and fixed a real orientation bug in the process. (§1)</li>
<li><strong>Under-specifying K_init merges true factors together</strong>, as expected; over-specification remains safe (unchanged from 8/27). (§4)</li>
<li><strong>Multi-modality extension is out of scope for now</strong> — no such data exists yet, and the current preprocessing can’t represent it structurally. (§5)</li>
</ul>
<p><code>chapters/2026-08-27.qmd</code> is the pre-meeting record and is not altered here.</p>
<hr>
</section>
<section id="clarifying-the-827-results" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="clarifying-the-827-results"><span class="header-section-number">8.1</span> §1 — Clarifying the 8/27 results</h2>
<p><strong>Was the log-likelihood/BIC used to pick K_init cross-validated?</strong> No — <code>compute_joint_ll_bic()</code> fits on all 273 training patients and scores those same 273 patients, in-sample. That’s not wrong, but it isn’t what was implied at the meeting. Two things follow:</p>
<ul>
<li><strong>A genuine held-out version now exists</strong> (new <code>code/compute_cv_loglik.R</code>): a held-out Cox partial log-likelihood (5-fold CV) and a bi-cross-validated genomics log-likelihood (holding out patient AND gene blocks jointly — an ordinary held-out check doesn’t work here, since projecting a patient from their own expression and then scoring them against it improves with more factors regardless of real structure). Reported separately from in-sample BIC, never combined into a “cross-validated BIC” — the two correct for the same in-sample optimism under different justifications, so combining them double-corrects.</li>
<li><strong>Building the held-out check found a real bug, since fixed at the source</strong>: the model’s own sign-correction step (which flips a fit’s coefficients if training performance looks backwards) had the check itself backwards, due to a default assumption in the underlying statistics package that doesn’t hold for this kind of model. It <strong>did</strong> affect the in-sample BIC values (K_init=7’s BIC moves from 1,614,174 to a corrected 1,614,079 — small, doesn’t change which K_init BIC prefers). It does <strong>not</strong> affect the count of prognostic factors (sign-invariant by construction) or any headline external C-index (also sign-invariant, since it was previously reported via a symmetric convention that didn’t depend on this check being correct). It has since been fixed directly in the model’s fitting code, not just worked around downstream — the practical consequence is that every joint survival coefficient reported in this chapter (§3’s per-cohort values included) is now on a <em>correct and trustworthy</em> sign convention for the first time, rather than one requiring a symmetric workaround to interpret safely. Some coefficients that were reported earlier this session under the old (uncorrected) convention flip sign as a result — magnitudes and every qualitative conclusion drawn from them are unchanged; see §3.</li>
</ul>
<p><strong>Six criteria on K_init now, not four — and they still disagree, which is informative, not a problem:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_k_init_sweep_6panel.png" class="img-fluid figure-img"></p>
<figcaption>K_init consensus sweep, six panels. The top row and held-out survival log-likelihood score training-cohort fit; bi-CV genomics log-likelihood and external C-index (bottom right) test generalization.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Criterion</th>
<th>What it actually measures</th>
<th>Prefers</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ELBO / in-sample BIC</td>
<td>Training-cohort fit, dominated by the genomics reconstruction term</td>
<td>K_init=3</td>
</tr>
<tr class="even">
<td>In-sample log-likelihood</td>
<td>The same in-sample fit, decomposed differently from BIC (no complexity penalty)</td>
<td>K_init=15</td>
</tr>
<tr class="odd">
<td>Held-out survival log-likelihood</td>
<td>Survival generalization, still the training cohort</td>
<td>Drifts toward larger K, noisily</td>
</tr>
<tr class="even">
<td>Bi-cross-validated genomics log-likelihood</td>
<td>Genomics generalization, still the training cohort</td>
<td>K≈4</td>
</tr>
<tr class="odd">
<td><strong>External C-index</strong></td>
<td><strong>Generalization to genuinely new cohorts — the actual deployment question</strong></td>
<td><strong>Plateaus from K_init=7</strong></td>
</tr>
</tbody>
</table>
<p>(An earlier draft of this table listed in-sample log-likelihood alongside ELBO/BIC as also preferring K_init=3 — it doesn’t. <code>k_init_sweep_results.csv</code>’s <code>loglik_joint</code> column is highest at K_init=15 (-750,480) vs.&nbsp;-768,148 at K_init=3; ELBO and BIC penalize model complexity and log-likelihood does not, so the three needn’t agree, and here they don’t.)</p>
<p>Each answers a different question; the one closest to the deployment question (external C-index) is the one to trust. K_init=7 is the smallest K_init on that plateau — a parsimony argument, not a claim that the other criteria agree.</p>
<p><strong>The K_init=11 and 13 dips in that plateau are real, not a fluke of initialization.</strong> A restart-based check (15 random re-initializations per K) was run specifically to test whether these two K values just got unlucky starting points:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">K_init</th>
<th style="text-align: right;">Best restart (of n_init)</th>
<th style="text-align: right;">Restarts tried</th>
<th style="text-align: right;">Mean external C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.6279</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.5994</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.6295</td>
</tr>
<tr class="even">
<td style="text-align: right;">13</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.5390</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.6271</td>
</tr>
<tr class="even">
<td style="text-align: right;">15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.6270</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>They didn’t — the original fit (restart 1) was already the best of all 15 attempts at both K=11 and K=13. Why these two specific values land on a worse solution is still open.</p>
<hr>
</section>
<section id="are-retained-factors-sensitive-to-threshold-variation" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="are-retained-factors-sensitive-to-threshold-variation"><span class="header-section-number">8.2</span> §2 — Are retained factors sensitive to threshold variation?</h2>
<p>Two thresholds decide which latent factors count as biologically or prognostically meaningful: <code>beta_thresh</code> (minimum coefficient size to call a factor prognostic) and <code>pve_thresh</code> (minimum variance explained to call a factor genomics-active). Neither has ever been checked for sensitivity — until now.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_threshold_sensitivity_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>Number of retained prognostic factors at K_init=7 across the beta_thresh x pve_thresh grid.</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>The same 2 prognostic factors are retained across the entire practical range</strong>: <code>beta_thresh</code> from 1e-4 to 0.01 (a 100x span) and every <code>pve_thresh</code> tested. <code>pve_thresh</code> has no effect at all in this range.</li>
<li>Only the extremes change the count: no threshold at all keeps 4 factors; the old default of 0.05 keeps 0, at every K_init from 2 to 20.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_threshold_vs_kinit.png" class="img-fluid figure-img"></p>
<figcaption>Number of retained prognostic factors vs K_init at three beta_thresh values.</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>This does <strong>not</strong> show the retained-factor count staying flat around the K_init=11/13 dip (§1) — <code>threshold_vs_kinit.csv</code> shows K_survival_active=3 (not the usual 2) at K_init=11 under both <code>beta_thresh=0.001</code> and <code>0.01</code>, and at K_init=13 under <code>beta_thresh=0.001</code> (dropping to 1 under <code>0.01</code>). The dip in external C-index at K=11/13 is real (§1’s restart check), but it is not accompanied by a stable retained-factor count — the threshold analysis doesn’t explain the dip, it just shows the dip’s factor count is itself threshold-sensitive in a way the rest of the K_init range isn’t.</li>
<li>A related, simulation-only threshold (<code>rel_thresh</code>, requiring a factor’s coefficient to be within some fraction of the largest one) is confirmed <strong>not</strong> usable on this real data: the smaller of the two true prognostic factors sits at only 29% of the largest factor’s coefficient, so the simulation-calibrated cutoff (65%) would incorrectly discard it.</li>
<li>One remaining fairness question — do factors need their coefficients rescaled by how much their signal actually varies before comparing them to a single fixed threshold — checked directly: rescaling doesn’t change which factors are called prognostic here.</li>
</ul>
<hr>
</section>
<section id="cohort-membership-in-the-survival-term-performance-and-interpretability" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="cohort-membership-in-the-survival-term-performance-and-interpretability"><span class="header-section-number">8.3</span> §3 — Cohort membership in the survival term: performance and interpretability</h2>
<p><strong>The headline result: letting the survival coefficient vary by cohort (<code>beta_cohort_id</code>) performs statistically the same as the current model, and the value it adds is visibility into how each training cohort contributes to the learned factors — not a predictive-accuracy gain.</strong> Confirmed two ways below: on the real data, and with simulated ground truth.</p>
<p>Three ways cohort membership can enter this model now exist, and they are independent of each other:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cohort_id</code> (existing)</td>
<td>Absorbs per-gene platform/batch differences in the genomics data; never touches survival</td>
</tr>
<tr class="even">
<td><code>strata_id</code> (existing)</td>
<td>Lets each cohort have its own baseline survival risk; the coefficient on each factor stays shared</td>
</tr>
<tr class="odd">
<td><strong><code>beta_cohort_id</code> (new this session)</strong></td>
<td><strong>The only one where a factor’s survival coefficient itself is allowed to differ by cohort</strong></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\eta_i = \sum_k (YF)_{ik} \cdot \beta_k^{c(i)}
\]</span></p>
<p><span class="math inline">\(\eta_i\)</span> is patient <span class="math inline">\(i\)</span>’s risk score; <span class="math inline">\((YF)_{ik}\)</span> is how strongly patient <span class="math inline">\(i\)</span> expresses gene program <span class="math inline">\(k\)</span>; <span class="math inline">\(\beta_k^{c(i)}\)</span> is program <span class="math inline">\(k\)</span>’s survival coefficient in patient <span class="math inline">\(i\)</span>’s cohort. The per-cohort coefficients for a given program are shrunk toward <strong>zero</strong> by a shared, jointly-estimated prior (not toward each other, or toward an estimated common nonzero value) rather than estimated fully independently — what’s shared across cohorts is the <em>amount</em> of shrinkage, not a common coefficient. Cohorts with less data still borrow strength from the others, since that shared shrinkage amount is fit jointly across all cohorts’ data.</p>
<section id="performance-statistically-indistinguishable-from-the-current-model" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="performance-statistically-indistinguishable-from-the-current-model"><span class="header-section-number">8.3.1</span> Performance: statistically indistinguishable from the current model</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 3%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">K</th>
<th style="text-align: right;">Prognostic factors</th>
<th style="text-align: right;">Total kept factors</th>
<th style="text-align: right;">Mean external C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">joint_yfb</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.6267</td>
</tr>
<tr class="even">
<td style="text-align: left;">joint_yfb_cohort_L</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.5431</td>
</tr>
<tr class="odd">
<td style="text-align: left;">joint_yfb_beta_c</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.6279</td>
</tr>
<tr class="even">
<td style="text-align: left;">joint_yfb_all_c</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.5999</td>
</tr>
<tr class="odd">
<td style="text-align: left;">two_step_ebmf_cox</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.6008</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>(As a first check, the current model’s row above reproduces the previously-reported result exactly — mean external C=0.6267 — confirming this comparison starts from the right baseline.)</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_3way_percohort_cindex.png" class="img-fluid figure-img"></p>
<figcaption>External C-index by cohort for the three main performance arms. Dashed line = chance (C=0.5).</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 47%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Comparison</th>
<th style="text-align: right;">Diff</th>
<th style="text-align: right;">Lower</th>
<th style="text-align: right;">Upper</th>
<th style="text-align: left;">Significant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">joint_yfb_minus_joint_yfb_cohort_L</td>
<td style="text-align: right;">0.0835</td>
<td style="text-align: right;">0.0379</td>
<td style="text-align: right;">0.1322</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: left;">joint_yfb_minus_joint_yfb_beta_c</td>
<td style="text-align: right;">-0.0012</td>
<td style="text-align: right;">-0.0039</td>
<td style="text-align: right;">0.0011</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">18</td>
<td style="text-align: left;">joint_yfb_minus_joint_yfb_all_c</td>
<td style="text-align: right;">0.0268</td>
<td style="text-align: right;">0.0136</td>
<td style="text-align: right;">0.0417</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: left;">joint_yfb_minus_two_step_ebmf_cox</td>
<td style="text-align: right;">0.0259</td>
<td style="text-align: right;">-0.0067</td>
<td style="text-align: right;">0.0597</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><strong><code>beta_cohort_id</code>’s gap to the current model was not detected as statistically significant</strong> (pooled 95% CI includes zero, and is narrow) — the point estimate very slightly favors <code>beta_cohort_id</code> itself. A CI that includes zero means a difference wasn’t detected here, not proof that the two are equivalent; the honest read is “no evidence of a performance cost to letting the coefficient vary by cohort,” not “underperforms.” It also had a higher observed mean external C than the two-step alternative (factorize first, then fit survival separately) — a bootstrap CI is only reported here against the current model, not against two-step directly, so this is a point-estimate comparison, not a tested one.</li>
<li><strong><code>cohort_id</code> (the existing, genomics-side component) is significantly worse</strong>, and worse than the two-step alternative too — it visibly competes with the real prognostic signal rather than coexisting with it (prognostic factor count drops from 2 to 1). This is a genuine limitation of that existing component, not of the new one. A <code>strata_id</code>-only fit (cohort-specific baseline risk, no other change) is statistically indistinguishable from the current model too — a clean null, not a failure to report.</li>
<li>This ranking is identical no matter which of the 5 external validation cohorts is left out of the average — not an artifact of one small cohort. A second, independent check (held-out survival log-likelihood on the training cohorts, not external validation) reaches the same ranking <strong>among the three arms scored on a common (pooled) risk set</strong> — <code>joint_yfb_beta_c</code> &gt; <code>joint_yfb</code> &gt; <code>joint_yfb_cohort_L</code>, matching external C exactly. It does <strong>not</strong> extend to the two arms that use <code>strata_id</code> (<code>joint_yfb_all_c</code>, and a <code>strata_only</code> sub-arm not shown in the table above): stratifying the risk set by cohort changes the partial log-likelihood’s scale, not just its value, so those two arms’ held-out log-likelihoods (both far higher than the other three, around -354.8 vs.&nbsp;-445 to -451) reflect that different risk-set structure rather than a genuinely better fit, and are not comparable to the other three or to each other’s C-index ranking on this metric.</li>
</ul>
</section>
<section id="interpretability-seeing-how-cohorts-differ" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="interpretability-seeing-how-cohorts-differ"><span class="header-section-number">8.3.2</span> Interpretability: seeing how cohorts differ</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_percohort_beta.png" class="img-fluid figure-img"></p>
<figcaption>Per-cohort survival coefficients across all 7 factors. Only Programs 3 and 7 carry any signal at all – the other five are near-zero in both cohorts.</figcaption>
</figure>
</div>
</div>
</div>
<p>Allowing cohort-specific coefficients reveals that <strong>Program 3’s effect is almost entirely specific to CPTAC</strong> (magnitude 0.030 vs.&nbsp;0.0004 in TCGA_PAAD) — the current (shared-coefficient) model blends it into a single number (magnitude 0.0115) that is not accurate for either cohort individually. <strong>Program 7’s effect, by contrast, is consistent across both cohorts</strong> (magnitude 0.034 CPTAC, 0.039 TCGA_PAAD). Neither fact is visible from the current model or from external validation performance — it only shows up once cohort membership is allowed into the survival term. (The joint coefficients’ sign convention was corrected this session — see the fix-plan work above these results — so these values are stated by magnitude; which cohort dominates which program, the ratio between them, and each program’s adverse/protective label from marginal association, DECISIONS.md 2026-06-16, are unaffected by that fix.) This is exactly the kind of “does the model actually handle multiple cohorts sensibly” evidence that would matter for comparison against methods like DeSurv or plain unsupervised factorization, none of which represent per-cohort effects at all.</p>
<p><strong>This was confirmed a second way, with simulated ground truth</strong>, not just observed as a pattern in real data: a simulation was built where a factor is <em>known</em> by construction to be prognostic in one cohort and not the other.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Median over 10 simulated replicates.</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 24%">
<col style="width: 32%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">K_init</th>
<th style="text-align: right;">Shared coefficient</th>
<th style="text-align: right;">True cohort’s coefficient</th>
<th style="text-align: right;">Other cohort’s coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.0613</td>
<td style="text-align: right;">0.0600</td>
<td style="text-align: right;">0.0085</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.0594</td>
<td style="text-align: right;">0.0542</td>
<td style="text-align: right;">0.0075</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><code>beta_cohort_id</code> correctly attributes the effect to the true cohort in a clear majority of cases (roughly 7x larger coefficient in the true cohort vs.&nbsp;the other, in 15–17 of 20 test cases). The value again wasn’t a bigger number — the shared coefficient already sat close to the true cohort’s value — it was that only the cohort-specific version makes that attribution visible at all.</p>
</section>
<section id="three-supporting-technical-notes" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="three-supporting-technical-notes"><span class="header-section-number">8.3.3</span> Three supporting technical notes</h3>
<ul>
<li><strong>Does pooling the two training cohorts actually help, or would one alone do just as well?</strong> Asserted in the 8/21 notes, never tested — tested now: the current model refit on TCGA_PAAD alone (n=144) or CPTAC alone (n=129) reaches mean external C of 0.514 and 0.578 respectively, well below the pooled fit’s 0.627 (and TCGA_PAAD-alone loses a prognostic factor, 2→1). This is consistent with pooling helping, but the comparison isn’t a clean isolation of pooling’s effect: refitting on a single cohort changes both the sample size AND the gene-selection step (each cohort’s own top-3000 genes, not the pooled 2064-gene set), so sample size and gene selection are confounded here, not separated.</li>
<li><strong>Why does the existing <code>cohort_id</code> component compete with prognostic signal instead of coexisting with it?</strong> Tested directly: refitting it from a better starting point (instead of a fresh random start) recovers both prognostic factors and closes most of its performance gap (external C rises from 0.543 to 0.617). So this is a model-fitting quirk, not a fundamental conflict between the two components.</li>
<li><strong>Why do this model’s kept gene programs resemble the highest-variance programs an unsupervised method would find anyway</strong>, rather than uncovering a lower-variance program invisible to unsupervised methods? Checked directly in the code: by design, the current model’s gene-program-DISCOVERY step (the F update) does not receive any feedback from survival at all — its update formula is identical to running an unsupervised factorization, and only the <em>selection</em> of which discovered programs are prognostic is supervised. This is not quite the same as saying survival has zero influence on the fit overall: survival still affects which iterate the CAVI loop converges to and returns via the joint stopping rule, since that rule is driven by the FULL objective (genomics and survival together), not the genomics term alone. Finding a genuinely low-variance, otherwise-overlooked prognostic program would require a more direct change (letting survival influence which programs are discovered, not just which are kept, or which iterate is selected) — a real, currently-disabled option flagged for future work (<code>ROADMAP.md</code>).</li>
</ul>
<hr>
</section>
</section>
<section id="other-findings" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="other-findings"><span class="header-section-number">8.4</span> §4 — Other findings</h2>
<p><strong>Under-specifying K_init merges true factors together, as expected.</strong> Giving the model fewer starting factors than truly exist causes genuinely distinct factors to blend into one; over-specifying (more starting factors than needed) remains safe, unchanged from 8/27. Checked directly, factor by factor: <strong>7 of 27 estimated factors show a clear merge signature (correlating substantially with two different true factors at once) when under-specified; 0 of 114 do at the true K_init or above.</strong> (This diagnostic is from a single simulated replicate — exploratory, not aggregated across the 15-seed replicate set the rest of this section’s numbers are averaged over; treat the specific counts as illustrative of the pattern rather than a precise estimate of its frequency.)</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_multicohort_delta_fig.png" class="img-fluid figure-img"></p>
<figcaption>Joint model’s C-index advantage over an unsupervised comparison, by scenario and number of starting factors, +-1 SE over 15 simulated replicates. From the true number of factors (6) upward, the advantage is stable and, in the scenario with a mix of shared and cohort-specific structure, substantial. Below 6, the picture is scenario-dependent, not uniformly flat or negative – see body text.</figcaption>
</figure>
</div>
</div>
</div>
<p>(The caption above corrects an earlier draft that described the advantage as “flat or negative” below K=6 in every scenario. <code>multicohort_delta_summary.csv</code> shows this holds for the <code>all_shared</code> and <code>nothing_shared</code> scenarios, but not for <code>hybrid</code> [mixed shared/cohort-specific structure]: there, the advantage is strongly POSITIVE below K=6, peaking at K_init=4 (+0.157), larger than at the true K_init=6 [+0.095]. Under-specifying K in a mixed-structure setting can apparently still find a useful, if merged, factor.)</p>
<p><strong>This model’s 4 kept gene programs were compared against an unsupervised factorization</strong> (no performance metric — a comparison of which genes each method’s programs are built from, not which predicts better).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-09-04_factor_comparison_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>This model’s 4 kept programs vs.&nbsp;all 40 unsupervised factors, ordered by variance explained (left = highest). All 4 land in the unsupervised method’s own top 5 – not buried deep in its ranking, which is the direct explanation for the second technical note in §3.</figcaption>
</figure>
</div>
</div>
</div>
<p>All 4 map cleanly onto the unsupervised method’s own top 5 (of 40) programs by variance explained (hypergeometric overlap p-values as low as 1e-129) — not buried deep in the unsupervised ranking, which is the direct explanation for the second technical note in §3. These p-values are descriptive, not inferential: both sets of gene programs are derived from the same expression matrix, so their gene-selection events are correlated by construction, not independent samples — read them as “this overlap is large,” not as a formal hypothesis test.</p>
<hr>
</section>
<section id="where-the-value-add-goes-next" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="where-the-value-add-goes-next"><span class="header-section-number">8.5</span> §5 — Where the value-add goes next</h2>
<p>Multi-modality extension (methylation, matched multi-view data) is out of scope: no such data exists yet, and the current data-merging step combines patients into one table in a way that can’t represent multiple feature types per patient. A prerequisite for that direction, not a decision against it.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/2026-08-27.html" class="pagination-link" aria-label="August 27, 2026">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">August 27, 2026</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>