<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Walther">

<title>SSBMF Status Update: Preprocessing Comparison, Cohort Indicator, and Final Configuration (May 27, 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="SSBMF_Status_Update_5_27_26_files/libs/clipboard/clipboard.min.js"></script>
<script src="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/quarto.js"></script>
<script src="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/popper.min.js"></script>
<script src="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/anchor.min.js"></script>
<link href="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SSBMF_Status_Update_5_27_26_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SSBMF_Status_Update_5_27_26_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SSBMF_Status_Update_5_27_26_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SSBMF_Status_Update_5_27_26_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../../SSBMF_Status_Update_5_27_26.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SSBMF Status Update: Preprocessing Comparison, Cohort Indicator, and Final Configuration (May 27, 2026)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Walther </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="objectives-and-decisions-addressed-since-last-update" class="level2">
<h2 class="anchored" data-anchor-id="objectives-and-decisions-addressed-since-last-update">1. Objectives and Decisions Addressed Since Last Update</h2>
<p>This report covers three questions that arose from the May 8 update and have now been resolved through a comprehensive 18-configuration benchmark on merged TCGA_PAAD + CPTAC training data (<span class="math inline">\(n = 273\)</span>, 5-fold CV K-selection with biological floor <span class="math inline">\(K \geq 3\)</span>, evaluated on 5 external cohorts).</p>
<ul>
<li><p><strong>Which preprocessing strategy is compatible with merged multi-platform training?</strong> Five strategies compared: joint quantile normalization + rank transform (prior standard), per-platform z-standardization, joint QN without rank transform, joint z-standardization, and log-transform only.</p></li>
<li><p><strong>Does the cohort indicator column in <span class="math inline">\(L\)</span> improve generalization?</strong> The cohort indicator absorbs the RNA-seq vs.&nbsp;proteomics platform offset at the model level (as opposed to removing it in preprocessing). Evaluated for both LB and YFB across preprocessing strategies.</p></li>
<li><p><strong>LB vs.&nbsp;YFB for the final manuscript configuration?</strong> LB (<span class="math inline">\(\eta = L\beta\)</span>) requires an OLS approximation to score new subjects (<span class="math inline">\(\hat{L}_{\text{new}} \approx Y_{\text{new}} F (F^\top F)^{-1}\)</span>). YFB (<span class="math inline">\(\eta = (YF)\beta\)</span>) scores new subjects exactly (<span class="math inline">\(\eta_{\text{new}} = Y_{\text{new}} F \beta\)</span>) with no approximation.</p></li>
</ul>
</section>
<section id="key-results-18-configuration-benchmark" class="level2">
<h2 class="anchored" data-anchor-id="key-results-18-configuration-benchmark">2. Key Results: 18-Configuration Benchmark</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>18-configuration benchmark sorted by model form (LB then YFB). <span class="math inline">\(K_{\text{eff}}\)</span> = active factors (<span class="math inline">\(|\hat{\beta}_k| &gt; 0.001\)</span>) after convergence. = <span class="math inline">\(\hat{\beta} = 0\)</span> for all factors.</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 18%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 22%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Preprocessing</th>
<th style="text-align: center;">Cohort</th>
<th style="text-align: center;">K</th>
<th style="text-align: center;"><span class="math inline">\(K_{\text{eff}}\)</span></th>
<th style="text-align: right;">Mean C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">M1</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint QN+rank</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0.599</td>
</tr>
<tr class="even">
<td style="text-align: left;">M2</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint QN+rank</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">3</td>
<td style="text-align: right;">0.619</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M3</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Per-plat z-std</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0.620</td>
</tr>
<tr class="even">
<td style="text-align: left;">M4</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Per-plat z-std</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0.624</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M7</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint QN</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0.598</td>
</tr>
<tr class="even">
<td style="text-align: left;">M8</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint QN</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0.615</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M9</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint z-std</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.545 ()</td>
</tr>
<tr class="even">
<td style="text-align: left;">M10</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Joint z-std</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.555 ()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M11</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Log only</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.533 ()</td>
</tr>
<tr class="even">
<td style="text-align: left;">M12</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Log only</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.531 ()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M5</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Per-plat z-std</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: right;">0.626</td>
</tr>
<tr class="even">
<td style="text-align: left;">M6</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Per-plat z-std</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: right;">0.613</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M13</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Joint QN</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.540 ()</td>
</tr>
<tr class="even">
<td style="text-align: left;">M14</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Joint QN</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.529 ()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M15</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Joint z-std</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.562 ()</td>
</tr>
<tr class="even">
<td style="text-align: left;">M16</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Joint z-std</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.543 ()</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M17</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Log only</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.529 ()</td>
</tr>
<tr class="even">
<td style="text-align: left;">M18</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Log only</td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0.532 ()</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Critical finding:</strong> 10 of 12 non-per-platform configurations produce <span class="math inline">\(\hat{\beta} = 0\)</span> for all factors (<span class="math inline">\(K_{\text{eff}} = 0\)</span>). The only viable preprocessing for merged RNA-seq + proteomics training is per-platform z-standardization applied before merging.</p>
</section>
<section id="preprocessing-why-per-platform-z-standardization-is-required" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing-why-per-platform-z-standardization-is-required">3. Preprocessing: Why Per-Platform Z-Standardization Is Required</h2>
<p>When TCGA_PAAD (RNA-seq) and CPTAC (proteomics) expression matrices are stacked without per-platform normalization, the top singular vectors of the merged <span class="math inline">\(Y\)</span> matrix capture the platform contrast, not biological variation. The CAVI survival update receives near-zero signal in these directions, so <span class="math inline">\(\hat{\beta} \to 0\)</span> regardless of model form or further normalization. Rank transform (M13/M14 vs.&nbsp;joint QN): removing the rank transform from joint-QN data does prevent YFB collapse, ruling out rank transform as the mechanism. The root cause is the platform-dominated SVD shared by all joint preprocessing strategies.</p>
<p>Per-platform z-standardization removes each cohort’s gene-level mean and variance merging. This makes the joint expression matrix reflect within-platform biological variation rather than between-platform scale differences. After per-platform z-std, both LB and YFB recover non-zero <span class="math inline">\(\hat{\beta}\)</span> at <span class="math inline">\(K = 3\)</span>.</p>
</section>
<section id="cohort-indicator-when-it-helps-vs.-when-it-hurts" class="level2">
<h2 class="anchored" data-anchor-id="cohort-indicator-when-it-helps-vs.-when-it-hurts">4. Cohort Indicator: When It Helps vs.&nbsp;When It Hurts</h2>
<p>The cohort indicator appends a platform dummy to <span class="math inline">\(L\)</span> and estimates a cohort-specific gene profile <span class="math inline">\(F_{\text{coh}}\)</span> via Normal conjugate update. Its effect depends on whether preprocessing has already removed the platform offset:</p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th style="text-align: right;">Cohort indicator effect</th>
<th>Mechanism</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LB + joint QN (M1→M2)</td>
<td style="text-align: right;">+0.020</td>
<td>Absorbs platform offset; frees 2 extra biological factors</td>
</tr>
<tr class="even">
<td>LB + per-platform z-std (M3→M4)</td>
<td style="text-align: right;">+0.004</td>
<td>Marginal; preprocessing already removed bulk offset</td>
</tr>
<tr class="odd">
<td>YFB + per-platform z-std (M5→M6)</td>
<td style="text-align: right;">−0.013</td>
<td>At <span class="math inline">\(K=3\)</span>, cohort column competes for variance with 2 biological factors</td>
</tr>
<tr class="even">
<td>LB + joint QN, low <span class="math inline">\(K\)</span> (K=5)</td>
<td style="text-align: right;">Essential</td>
<td>Without it, LB also collapses to <span class="math inline">\(K_{\text{eff}}=0\)</span> at <span class="math inline">\(K=5\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Recommendation on cohort indicator:</strong> It is most valuable as a <strong>robustness feature for LB when per-platform preprocessing cannot be guaranteed</strong> (e.g., adding a new cohort to an existing fit without retraining). For the primary analysis configuration (YFB + per-platform z-std), it is at low <span class="math inline">\(K\)</span> and should be excluded. For sensitivity analysis (LB + per-platform z-std, M4), it is effectively neutral (+0.004) and can be included without cost. Future work extending to 3+ cohorts should revisit the cohort indicator, as it may provide greater benefit when platform contrast is larger.</p>
</section>
<section id="recommendation-final-configuration-for-manuscript" class="level2">
<h2 class="anchored" data-anchor-id="recommendation-final-configuration-for-manuscript">5. Recommendation: Final Configuration for Manuscript</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Recommended configurations. D4 (primary) uses K=7 (CV-selected) with DeSurv-aligned gene selection; M4 (sensitivity) uses K=3 (biological floor).</caption>
<colgroup>
<col style="width: 1%">
<col style="width: 10%">
<col style="width: 3%">
<col style="width: 25%">
<col style="width: 4%">
<col style="width: 1%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Role</th>
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Preprocessing</th>
<th style="text-align: left;">Cohort</th>
<th style="text-align: right;">K</th>
<th style="text-align: right;">K_eff</th>
<th style="text-align: right;">Mean C</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Primary (D4)</td>
<td style="text-align: left;">YFB</td>
<td style="text-align: left;">Per-platform z-std + DeSurv gene selection</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.636</td>
<td style="text-align: left;">DeSurv-aligned gene selection (+0.012 vs M5); 2 active programs; highest C</td>
</tr>
<tr class="even">
<td style="text-align: left;">M4</td>
<td style="text-align: left;">Sensitivity (M4)</td>
<td style="text-align: left;">LB</td>
<td style="text-align: left;">Per-platform z-std</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.624</td>
<td style="text-align: left;">Explicit platform offset model; LB robustness check</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>D4 (primary; supersedes M5):</strong> YFB with DeSurv-aligned gene selection (combined mean+variance rank, top-3000 genes per cohort selected on log-transformed data before per-platform z-standardization) identifies 2 active gene expression programs (<span class="math inline">\(K_{\text{eff}} = 2\)</span>) from 7 learned factors, with mean external C = 0.636 across 5 independent PDAC cohorts (Dijk, Moffitt GEO, PACA-AU array, PACA-AU seq, Puleo). This supersedes M5 (mean C = 0.626, K=3): the DeSurv gene selection yields <span class="math inline">\(\Delta C = +0.012\)</span>, exceeding the pre-specified <span class="math inline">\(\pm 0.005\)</span> practical threshold, with improvement in 4 of 5 external cohorts. New-patient risk scores require only <span class="math inline">\(\eta_{\text{new}} = Y_{\text{new}} F \hat\beta\)</span> — no sample-level latent variable approximation. Factor loadings <span class="math inline">\(F\)</span> are directly interpretable as gene weights defining each prognostic program. See <code>docs/reports/desurv_alignment_report_05_27_26.pdf</code> for the full D1–D4 comparison.</p>
<p><strong>M4 (sensitivity):</strong> LB with cohort indicator reaches mean C = 0.624 — effectively tied with M5 — and explicitly encodes the RNA-seq vs.&nbsp;proteomics platform difference as a model parameter rather than a preprocessing step.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="summary-figure" class="level2">
<h2 class="anchored" data-anchor-id="summary-figure">6. Summary Figure</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SSBMF_Status_Update_5_27_26_files/figure-html/summary-fig-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Left: mean external C-index for all 18 configurations, colored by model type. Dashed line = chance (C=0.5). Grey fill = configurations with K_eff=0 (beta collapse). Right: per-cohort C-index for the two recommended configurations.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="open-items-and-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="open-items-and-next-steps">7. Open Items and Next Steps</h2>
<ul>
<li><p><strong>Pathway enrichment on D4 factors.</strong> DeSurv-aligned gene selection changes the training gene set (2064 genes vs 2000); re-run GSEA/ORA on D4 factor loadings once adopted.</p></li>
<li><p><strong>Gene set enrichment / pathway analysis</strong> for D4 (formerly M5) factors 1 and 2 (the 2 active prognostic programs). This is the primary interpretability task remaining before the manuscript methods section can be finalized.</p></li>
<li><p><strong>Cohort indicator for future multi-cohort extensions.</strong> As the training set grows beyond 2 platforms (e.g., adding microarray cohorts), the cohort indicator may become more valuable. The <code>cohort_id</code> parameter is already implemented in both LB and YFB; the cost/benefit analysis above applies per-pair of preprocessing choices and <span class="math inline">\(K\)</span>.</p></li>
<li><p><strong>Single-cohort YFB.</strong> YFB on TCGA-only or CPTAC-only still has near-zero betas (lack of platform contrast means the SVD directions are more biological, but <span class="math inline">\(n\)</span> is too small for stable CV). Not blocking for the merged-cohort manuscript.</p></li>
<li><p><strong>LB prediction approximation.</strong> The OLS approximation for LB new-subject scoring is adequate for sensitivity analysis but should be noted as a limitation vs.&nbsp;YFB. A potential alternative: train YFB on TCGA-only + CPTAC-only separately and compare factor consistency across platforms as a validation experiment.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>