<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Walther">

<title>SSBMF Status Update: Model Refinement, Validation, and Biological Interpretation (August 3, 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="SSBMF_Status_Update_08_03_26_files/libs/clipboard/clipboard.min.js"></script>
<script src="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/quarto.js"></script>
<script src="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/popper.min.js"></script>
<script src="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/anchor.min.js"></script>
<link href="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SSBMF_Status_Update_08_03_26_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SSBMF_Status_Update_08_03_26_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SSBMF_Status_Update_08_03_26_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SSBMF_Status_Update_08_03_26_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../../SSBMF_Status_Update_08_03_26.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SSBMF Status Update: Model Refinement, Validation, and Biological Interpretation (August 3, 2026)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Walther </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><strong>Selected model:</strong> <strong>YFB</strong> (<span class="math inline">\(\eta = (YF)\hat\beta\)</span>), with DeSurv-aligned gene selection, <span class="math inline">\(K=7\)</span> latent programs, and no cohort indicator.</li>
<li><strong>Selected factors:</strong> the model uses <strong>2 of its 7 programs</strong> for survival prediction (<span class="math inline">\(K_{\text{eff}}=2\)</span>) — matching DeSurv’s own ~1 prognostic factor, and robust across independent checks, not a tuning artifact.</li>
<li><strong>Performance:</strong> <strong>mean external C-index = 0.627 across 5 held-out PDAC cohorts</strong>, significantly more concordant than a two-step baseline when pooled across cohorts (+0.042, 95% CI 0.013–0.071).</li>
<li><strong>Other key findings:</strong> the joint model’s advantage over a two-step (factorize-then-Cox) baseline widens as survival signal strength increases; the two survival-active programs are biologically distinct and correspond to the established PDAC adverse (basal-like) / protective (classical) subtype axis, confirmed by five independent methods.</li>
</ul>
</section>
<section id="recent-progress" class="level2">
<h2 class="anchored" data-anchor-id="recent-progress">Recent Progress</h2>
<ul>
<li><strong>Objective put on a principled footing.</strong> The genomics/survival scale imbalance the lab flagged was addressed; the redundant <span class="math inline">\(\lambda\)</span> mixing parameter was retired (<span class="math inline">\(\alpha\)</span> already plays its role). Honest finding: for YFB this gave <strong>no performance change</strong> — its genomics half and survival half never share a coordinate needing rebalancing. A separate train/test preprocessing bug (external cohorts were rank-transformed while training was per-platform z-standardized — the reverse) was fixed; <strong>this fix alone</strong> explains the headline moving from 0.636 to <strong>0.627</strong> (a correction, not a regression).</li>
<li><strong>Why 7 factors when DeSurv used 3?</strong> Cross-validation genuinely selects <span class="math inline">\(K=7\)</span>, but only <strong>2 factors are survival-active</strong> (<span class="math inline">\(K_{\text{eff}}=2\)</span>, defined as <span class="math inline">\(|\hat\beta_k|\)</span> exceeding a fixed threshold of 0.001) — matching DeSurv’s own ~1 prognostic factor. Two independent optimization strategies (warm-start from a higher-<span class="math inline">\(K\)</span> fit, and a joint <span class="math inline">\((K,\alpha)\)</span> Bayesian-optimization search) both land on <span class="math inline">\(K_{\text{eff}}=2\)</span>, and a deflation-initialization test analytically ruled out initialization as the cause of an earlier ambiguity; <span class="math inline">\(K\in\{4,5,7,8\}\)</span> are statistically indistinguishable (spread 0.0015). <span class="math inline">\(K=7\)</span> is kept only for one-step reproducibility; <span class="math inline">\(K=4/K=5\)</span> are validated equivalents.</li>
<li><strong>Study-specific baseline hazard.</strong> Implemented the requested <code>+ strata(study)</code> as an optional stratified Cox partial likelihood. Performance-neutral (0.6267 → 0.6263), so available but off by default.</li>
<li><strong>Biological interpretation of the two active programs.</strong> Complete, and confirmed by five independent methods.</li>
</ul>
</section>
<section id="validation-across-simulated-and-real-data" class="level2">
<h2 class="anchored" data-anchor-id="validation-across-simulated-and-real-data">Validation across simulated and real data</h2>
<p><strong>Simulation — joint model vs.&nbsp;a two-step (factorize-then-Cox) baseline</strong> (re-confirmed under the corrected model this cycle):</p>
<ul>
<li><em>Turn survival signal up from zero:</em> at zero signal, joint <span class="math inline">\(\approx\)</span> two-step (both near chance); as signal grows, the joint model pulls ahead and the gap widens, in 3 of 4 data-generating designs. One artificial design (exactly-sparse, symmetric factor loadings) reverses this — traced to a specific, understood factor-collapse failure mode, not a survival-coupling defect.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../results/multi_cohort_sim/outputs/survival_strength_sweep_plot.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Each of the 4 panels is a different simulation design (default = realistic factor-loading templates; sparse_synthetic = an artificial exact-sparse stress test; low_snr = weakened shared genomic signal; high_K = more shared latent factors) – the panels are not different models. Within every panel, the x-axis is prognostic effect strength and the 4 colored lines are the models being compared: YFB (recommended, joint) and LB (the other joint variant) against two two-step baselines, PCA+Cox and EBMF+Cox. YFB pulls ahead of both two-step baselines as signal strength increases in 3 of 4 panels, with the gap widening through the highest signal level tested; the one reversal (sparse_synthetic) is the known factor-collapse artifact noted above, not a general failure of the joint approach.</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><em>Shared vs.&nbsp;study-specific factors:</em></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Held-out C-index by cross-cohort factor structure (5 seeds).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: right;">Joint (YFB)</th>
<th style="text-align: right;">Two-step (EBMF+Cox)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All factors shared</td>
<td style="text-align: right;">0.871</td>
<td style="text-align: right;">0.856</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hybrid (some shared, some specific)</td>
<td style="text-align: right;">0.815</td>
<td style="text-align: right;">0.717</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No shared prognostic factors</td>
<td style="text-align: right;">0.549</td>
<td style="text-align: right;">0.550</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When no shared prognostic signal exists, joint and two-step are equivalent; in the realistic hybrid case (only some factors prognostic) the joint model leads — as much through <strong>stability</strong> as accuracy: the unsupervised two-step baseline collapses on 2 of 5 seeds (dragging its mean to 0.717), while the joint model is stable across all seeds (mean 0.815) and classifies each factor as shared vs. study-specific with perfect accuracy.</p>
<div style="page-break-after: always;"></div>
<p><strong>Real data — 5 held-out PDAC cohorts</strong> (RNA-seq, microarray, proteomics):</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>External validation with 95% bootstrap CI (mean = 0.627).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Held-out cohort</th>
<th style="text-align: right;">External C-index</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PACA_AU_seq</td>
<td style="text-align: right;">0.657</td>
<td style="text-align: left;">(0.544, 0.772)</td>
</tr>
<tr class="even">
<td style="text-align: left;">PACA_AU_array</td>
<td style="text-align: right;">0.648</td>
<td style="text-align: left;">(0.553, 0.747)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puleo_array</td>
<td style="text-align: right;">0.645</td>
<td style="text-align: left;">(0.599, 0.688)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dijk</td>
<td style="text-align: right;">0.634</td>
<td style="text-align: left;">(0.555, 0.708)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moffitt_GEO_array</td>
<td style="text-align: right;">0.549</td>
<td style="text-align: left;">(0.467, 0.625)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Four of five cohorts clear chance with their CI lower bound above 0.5; <strong>Moffitt microarray does not</strong> (CI 0.467–0.625), confirming quantitatively what was previously only a qualitative flag. <strong>Against a two-step (unsupervised EBMF then Cox) baseline on the same patients, a paired bootstrap finds the recommended model significantly more concordant when pooled across all 5 cohorts: +0.042 (95% CI 0.013–0.071).</strong> Individually only the largest cohort (Puleo, <span class="math inline">\(n=288\)</span>) reaches significance alone; the other four all favor the recommended model but are underpowered on their own. Per-platform z-standardization is essential — most non-per-platform preprocessing collapses the survival coefficients to zero.</p>
<p><em>Bootstrap method:</em> both the per-cohort CIs above and the paired comparison use patient-level bootstrap resampling within each cohort (2000 replicates, percentile CI). The paired comparison resamples patients once per replicate and scores both models on that identical draw, preserving the correlation between their errors on shared patients — a more powerful (and correct) test than comparing two independently-computed CIs. The 5 per-cohort differences are then combined via a fixed-effect, inverse-variance-weighted pooled estimate.</p>
</section>
<section id="biology-of-the-two-active-programs" class="level2">
<h2 class="anchored" data-anchor-id="biology-of-the-two-active-programs">Biology of the two active programs</h2>
<p>An <strong>adverse</strong> program (basal-like / squamous / MET-EGFR-driven) and a <strong>protective</strong> program (classical / differentiated-epithelial) — the established PDAC subtype-survival axis. Confirmed by five independent methods: gene-set enrichment, PurIST (Purity Independent Subtyping of Tumors; Rashid et al.&nbsp;2020) subtype concordance (<span class="math inline">\(\rho=\pm0.58\)</span>), external-cohort hazard ratios (adverse HR&gt;1 in 5/5 cohorts, protective HR&lt;1 in 5/5), and direct gene-list overlap with DeSurv’s published programs.</p>
<p><strong>Methods for the five checks above:</strong></p>
<ul>
<li><strong>Gene-set enrichment</strong> — <code>fgsea</code>, ranked by each program’s posterior mean gene weight (the model’s own <span class="math inline">\(E[F]\)</span> column, no re-ranking), tested against MSigDB Hallmark/Reactome/KEGG/GO:BP plus a custom PDAC gene-set collection (Moffitt basal/classical, Bailey 2016, DeSurv D1–D3); ORA on the top 50/100/150-weighted genes serves as a confirmatory cross-check. The figure below pools the <code>fgsea</code>-defined <strong>leading-edge genes</strong> (the genes actually driving each set’s enrichment score, up to 20 per set) across every significant set (<span class="math inline">\(\text{padj}&lt;0.10\)</span>) for Programs 3 and 7; heatmap rows are hierarchically clustered (Euclidean distance, complete linkage) on their weight profile across all 7 programs, columns are fixed in program order, and color is the raw posterior mean weight.</li>
<li><strong>PurIST concordance</strong> — Spearman correlation between each patient’s posterior mean program loading and their PurIST basal-likelihood probability (TCGA-PAAD, the only cohort with PurIST calls available).</li>
<li><strong>External-cohort hazard ratios</strong> — a univariate Cox model, per cohort, of a leading-edge gene-signature score (mean per-gene z-score across that program’s leading-edge genes) against overall survival.</li>
<li><strong>DeSurv gene overlap</strong> — hypergeometric test and Jaccard index between each program’s top-270-weighted genes and DeSurv’s published per-factor gene lists.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../results/benchmark_sim/outputs/pathway_enrichment/F3_geneweight_heatmap.png" class="img-fluid figure-img" style="width:65.0%"></p>
<figcaption class="figure-caption">Gene weights across all 7 programs, for the union of each active program’s leading-edge genes: a clean block-diagonal structure – Program 3’s and Program 7’s genes carry weight almost exclusively in their own column, and the other 5 programs carry essentially none. This visually confirms the two active programs are biologically distinct, non-overlapping gene sets, consistent with the PurIST concordance, external-cohort hazard-ratio, and DeSurv gene-overlap evidence above.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="comparison-against-desurv" class="level2">
<h2 class="anchored" data-anchor-id="comparison-against-desurv">Comparison against DeSurv</h2>
<ul>
<li><strong>Factor count:</strong> SBMF’s CV-selected <span class="math inline">\(K=7\)</span> collapses to <span class="math inline">\(K_{\text{eff}}=2\)</span> survival-active programs — closely matching DeSurv’s own ~1 prognostic factor, via two independent confirmation strategies (see Recent Progress above).</li>
<li><strong>Gene selection overlap:</strong> Program 7 (Adverse) overlaps DeSurv’s basal-like-tumor factor at Jaccard 0.18 (hypergeometric <span class="math inline">\(p\approx3\times10^{-16}\)</span>); Program 3 (Protective) overlaps DeSurv’s classical-tumor factor at Jaccard 0.13 (<span class="math inline">\(p\approx1\times10^{-7}\)</span>). Despite different model classes (empirical-Bayes factorization + Cox vs.&nbsp;DeSurv’s own framework), both methods converge on the same underlying tumor biology — that convergence, not a performance ranking, is the meaningful point of comparison here.</li>
</ul>
</section>
<section id="key-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="key-next-steps">Key next steps</h2>
<ol type="1">
<li>Characterize factor-stability across random seeds/initializations for the recommended YFB fit (not yet done).</li>
<li>Run a matched, same-protocol head-to-head against DeSurv (same data, same scoring), building on the gene-overlap comparison above.</li>
<li>Shift focus to manuscript writing (introduction and background/literature research) — the companion manuscript repository is already scaffolded with an intro draft and populated reference library; the next step is to continue and expand that draft.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>