<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SSBMF Progress Notebook - 6&nbsp; August 21, 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/2026-08-27.html" rel="next">
<link href="../chapters/2026-08-03.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/2026-08-21.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">August 21, 2026</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SSBMF Progress Notebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this notebook</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-04-29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">April 29, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">May 7, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-28.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">May 28, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-07-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">July 15, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">August 3, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-21.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">August 21, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-27.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">August 27, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-09-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">September 4, 2026</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#recent-updates" id="toc-recent-updates" class="nav-link" data-scroll-target="#recent-updates"><span class="header-section-number">6.1</span> Recent Updates</a>
  <ul class="collapse">
  <li><a href="#completed" id="toc-completed" class="nav-link" data-scroll-target="#completed"><span class="header-section-number">6.1.1</span> Completed</a></li>
  <li><a href="#items-to-address" id="toc-items-to-address" class="nav-link" data-scroll-target="#items-to-address"><span class="header-section-number">6.1.2</span> Items to address</a></li>
  <li><a href="#ongoing" id="toc-ongoing" class="nav-link" data-scroll-target="#ongoing"><span class="header-section-number">6.1.3</span> Ongoing</a></li>
  </ul></li>
  <li><a href="#model-specification-yfb" id="toc-model-specification-yfb" class="nav-link" data-scroll-target="#model-specification-yfb"><span class="header-section-number">6.2</span> Model Specification: YFB</a>
  <ul class="collapse">
  <li><a href="#generative-model" id="toc-generative-model" class="nav-link" data-scroll-target="#generative-model"><span class="header-section-number">6.2.1</span> Generative model</a></li>
  <li><a href="#the-full-model-likelihood-priors-and-posteriors" id="toc-the-full-model-likelihood-priors-and-posteriors" class="nav-link" data-scroll-target="#the-full-model-likelihood-priors-and-posteriors"><span class="header-section-number">6.2.2</span> The full model: likelihood, priors, and posteriors</a></li>
  <li><a href="#update-steps-one-outer-cavi-iteration" id="toc-update-steps-one-outer-cavi-iteration" class="nav-link" data-scroll-target="#update-steps-one-outer-cavi-iteration"><span class="header-section-number">6.2.3</span> Update steps (one outer CAVI iteration)</a></li>
  <li><a href="#gene-selection" id="toc-gene-selection" class="nav-link" data-scroll-target="#gene-selection"><span class="header-section-number">6.2.4</span> Gene selection</a></li>
  <li><a href="#factor-composition-k7" id="toc-factor-composition-k7" class="nav-link" data-scroll-target="#factor-composition-k7"><span class="header-section-number">6.2.5</span> Factor composition (<span class="math inline">\(K=7\)</span>)</a></li>
  </ul></li>
  <li><a href="#choosing-k-cv-for-external-c-index-vs.-k-selection-from-model-elbo" id="toc-choosing-k-cv-for-external-c-index-vs.-k-selection-from-model-elbo" class="nav-link" data-scroll-target="#choosing-k-cv-for-external-c-index-vs.-k-selection-from-model-elbo"><span class="header-section-number">6.3</span> Choosing <span class="math inline">\(K\)</span>: CV for external C-index vs.&nbsp;K-selection from model ELBO</a>
  <ul class="collapse">
  <li><a href="#k-selection-by-ard-pruning-and-elbo" id="toc-k-selection-by-ard-pruning-and-elbo" class="nav-link" data-scroll-target="#k-selection-by-ard-pruning-and-elbo"><span class="header-section-number">6.3.1</span> <span class="math inline">\(K\)</span> selection by ARD pruning and ELBO</a></li>
  <li><a href="#simulation-check-the-procedure-over-counts-survival-active-factors" id="toc-simulation-check-the-procedure-over-counts-survival-active-factors" class="nav-link" data-scroll-target="#simulation-check-the-procedure-over-counts-survival-active-factors"><span class="header-section-number">6.3.2</span> Simulation check: the procedure over-counts survival-active factors</a></li>
  <li><a href="#significance-of-the-k5-vs.-k7-gap" id="toc-significance-of-the-k5-vs.-k7-gap" class="nav-link" data-scroll-target="#significance-of-the-k5-vs.-k7-gap"><span class="header-section-number">6.3.3</span> Significance of the <span class="math inline">\(K=5\)</span> vs.&nbsp;<span class="math inline">\(K=7\)</span> gap</a></li>
  <li><a href="#gene-composition-of-the-kept-programs" id="toc-gene-composition-of-the-kept-programs" class="nav-link" data-scroll-target="#gene-composition-of-the-kept-programs"><span class="header-section-number">6.3.4</span> Gene composition of the kept programs</a></li>
  <li><a href="#joint-model-vs.-two-step-baseline" id="toc-joint-model-vs.-two-step-baseline" class="nav-link" data-scroll-target="#joint-model-vs.-two-step-baseline"><span class="header-section-number">6.3.5</span> Joint model vs.&nbsp;two-step baseline</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">August 21, 2026</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<p><strong>Model specification (§2).</strong> The full YFB model is written out: both likelihoods, the priors on each latent variable, the variational posteriors, and the ELBO the CAVI updates maximize. All four update formulas (<span class="math inline">\(\beta\)</span>, <span class="math inline">\(L\)</span>, <span class="math inline">\(F\)</span>, <span class="math inline">\(\tau\)</span>) are provided as well.</p>
<p><strong><span class="math inline">\(K\)</span> selection now uses ARD pruning plus ELBO, not cross-validated C-index (§3.1).</strong></p>
<ul>
<li>Fitting at <span class="math inline">\(K_{\text{init}} \in \{5,\dots,20\}\)</span> gives a stable <strong>2 survival-active factors for every <span class="math inline">\(K \ge 7\)</span></strong>; added capacity goes entirely to dead factors, which is due to ARD (see table in §3.1).</li>
<li><span class="math inline">\(K=5\)</span> has the best ELBO of the whole grid but generalizes far worse (C=0.596 vs.&nbsp;0.627); <span class="math inline">\(K=6\)</span> loses on both counts (worse ELBO than <span class="math inline">\(K=7\)</span>, and C=0.597). ELBO ranks candidate <span class="math inline">\(K\)</span>’s, but any <span class="math inline">\(K\)</span> that fails externally is excluded first.</li>
<li><strong><span class="math inline">\(K=7\)</span> (2 survival-active + 2 genomics-only = 4 kept factors) selected</strong>, with <span class="math inline">\(K=9\)</span> as a near-tied alternative. The <span class="math inline">\(K=5\)</span> vs.&nbsp;<span class="math inline">\(K=7\)</span> gap is significant pooled across cohorts (§3.3).</li>
<li>The fit is stable across starting points: 15 restarts per <span class="math inline">\(K\)</span> all reach the same best-ELBO solution, which closes the factor-stability question left open on 8/3.</li>
</ul>
<p><strong>The joint model outperforms an independent two-step baseline (§3.5).</strong> Against a baseline model (<span class="math inline">\(K\)</span>=40 never informed by YFB, LASSO at stage 2), YFB’s advantage is <strong>+0.026, 95% CI [0.0002, 0.0498]</strong> pooled across the 5 external cohorts, and it outperforms in all 6 configurations tested. A simulation reproduces the expected external C-index curve (equivalence at zero signal, YFB ahead as signal grows).</p>
<p><strong>Open discussion item:</strong> the selection procedure over-counts survival-active factors in simulation (§3.2). 41 of 45 fits found more than the true number, caused by small spurious survival coefficients attaching to real-but-non-prognostic programs. A relative-magnitude threshold fixes it in simulation but must not be applied to the real data, where it would discard Program 3 despite independent external confirmation. Needs a decision on how to handle this for future datasets.</p>
<p><strong>Factor biology (§2.5).</strong> Programs 3 and 7 were characterized in the July 15 cycle, where five independent methods agreed on Program 7 as adverse/basal-like and Program 3 as protective/classical. Extended this cycle to the 2 genomics-only factors, which had never been reported: Program 5 reads as desmoplastic stroma and Program 6 as immune infiltrate, and the 4 kept factors together recover DeSurv’s full 3-factor structure. The open question is process: this work was self-directed rather than group-directed, so the approach is worth confirming before the labels carry into the manuscript.</p>
<p><strong>Logistics.</strong> Finalize committee (Lin, Liu, Rashid, Hudgens, Van Deinse); prelim targeted for end of Fall 2026; 8/27 lab meeting preparation (topic aside from project update? Semester goal setting?).</p>
<p><strong>Questions</strong></p>
<ul>
<li>Selection of starting K value prior to pruning (tested a range and currently settled on 7)?</li>
<li>Settle on method for selecting K (CV uses survival data twice vs.&nbsp;pruning from larger starting value)</li>
<li>general scope for remainder of project</li>
</ul>
<hr>
</section>
<section id="recent-updates" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="recent-updates"><span class="header-section-number">6.1</span> Recent Updates</h2>
<p>The 8/3 entry closed two open questions about the two survival-active gene programs (Program 7, adverse; Program 3, protective): they reproduce in a fully unsupervised fit (not an artifact of the survival term), and they independently match DeSurv’s published basal-like/classical tumor axes. Focus then shifted toward the manuscript and toward a list of action items from that meeting. This section tracks each of those items, both the ones closed this cycle and the ones still open.</p>
<section id="completed" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="completed"><span class="header-section-number">6.1.1</span> Completed</h3>
<ul>
<li><strong>Bootstrap C-index confidence intervals + paired significance test</strong> (2026-07-16): wrote the bootstrap-CI code and used it to compare the recommended model against a two-step (unsupervised-factorization-then-Cox) baseline, finding a significant advantage. <strong>Re-examined this cycle (§3.5):</strong> that specific baseline had its own weaknesses (unregularized stage 2, an unmatched <span class="math inline">\(K\)</span>), so it was checked against a properly-built independent baseline instead. The advantage holds up.</li>
<li><strong>Consolidated progress notebook</strong> (this book): one chapter per advisor meeting, backfilled April 29 through August 3 and pushed 2026-08-03.</li>
<li><strong>Model specification write-up</strong>: the 8/3 notes’ top immediate item (“write out current model form, pseudo-algorithm and major update steps”) is §2 of this chapter, below.</li>
<li><strong>How <span class="math inline">\(K=7\)</span> was chosen, and whether that answer is trustworthy</strong> (2026-08-19/20, this cycle; §3 below): <span class="math inline">\(K=7\)</span> was originally chosen by cross-validated held-out C-index, which uses the survival outcome to pick model structure. This was the ARD-vs-cross-validation comparison raised at the last meeting. Re-derived it instead from model fit alone (ELBO), cross-checked against external validity, and separately stress-tested the procedure in a simulation where the true number of factors is known. See §3.</li>
<li><strong>Factor stability across random seeds</strong> (8/3 open item). Refitting each <span class="math inline">\(K \in \{5,\dots,10\}\)</span> from 15 different starting points (1 SVD initialization + 14 random) converged to the same best-ELBO solution every time, at every <span class="math inline">\(K\)</span>; random restarts never beat the SVD initialization. The 2 survival-active programs are therefore not an artifact of one lucky starting point.</li>
</ul>
</section>
<section id="items-to-address" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="items-to-address"><span class="header-section-number">6.1.2</span> Items to address</h3>
<ul>
<li><strong>Consistency of the 5 non-survival-active factors across the external cohorts.</strong> Programs 3 and 7 have been checked thoroughly (pathway enrichment, subtype correlation, DeSurv overlap, cross-cohort hazard ratios); the other factors in the <span class="math inline">\(K=7\)</span> fit have not had the equivalent check.</li>
<li><strong>Aligning on the factor-biology work</strong> (§2.5). This was pursued independently rather than at the group’s direction, so the approach needs review even though the existing results may turn out to be sufficient.</li>
<li>Slides/figures for the 8/27 lab meeting progress update, prepared separately from this chapter.</li>
<li><strong>Finalize committee:</strong> Dr.&nbsp;Lin, Dr.&nbsp;Liu, Dr.&nbsp;Rashid, Dr.&nbsp;Hudgens, Dr.&nbsp;Van Deinse (Social Work).</li>
<li><strong>Schedule prelim for end of Fall 2026.</strong></li>
</ul>
</section>
<section id="ongoing" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="ongoing"><span class="header-section-number">6.1.3</span> Ongoing</h3>
<ul>
<li>Weekly recurring meetings (Thursdays?) and a written update each time (this book).</li>
<li>Frequent pushes to the model repository &amp; writing in separate manuscript repo.</li>
<li>Prep for leading 8/27 lab meeting</li>
<li>The cohort-membership indicator (<code>cohort_id</code>) absorbs genomic platform offsets only; it never carries survival information, and is off by default (no observed benefit).</li>
</ul>
<hr>
</section>
</section>
<section id="model-specification-yfb" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="model-specification-yfb"><span class="header-section-number">6.2</span> Model Specification: YFB</h2>
<p>Current model form: <strong>“YFB” linear predictor in Cox model</strong> (<code>code/fit_cox_on_yf.R</code>), <span class="math inline">\(\eta = (YF)\beta\)</span>, referred to here as <strong>YFB</strong>.</p>
<section id="generative-model" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="generative-model"><span class="header-section-number">6.2.1</span> Generative model</h3>
<p><strong>Genomics model.</strong> The observed expression matrix is a low-rank product plus feature-specific Gaussian noise: <span class="math display">\[
Y = L F^\top + E, \qquad E_{ij} \sim \mathcal{N}\!\left(0, \tau_j^{-1}\right)
\]</span></p>
<ul>
<li><span class="math inline">\(Y\)</span> is <span class="math inline">\(n \times p\)</span> (patients <span class="math inline">\(\times\)</span> genes), column-centered.</li>
<li><span class="math inline">\(L\)</span> (<span class="math inline">\(n\times K\)</span>) is the patient-loading matrix: how strongly patient <span class="math inline">\(i\)</span> expresses gene program <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(F\)</span> (<span class="math inline">\(p \times K\)</span>) is the factor matrix: which genes, and how strongly, make up program <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(\tau_j\)</span> is gene <span class="math inline">\(j\)</span>’s noise precision (inverse variance). Each gene is allowed its own noise level.</li>
</ul>
<p><strong>Projection onto observed expression.</strong> Rather than scoring survival risk from the latent, uncertain loadings <span class="math inline">\(L\)</span>, YFB projects the <em>observed</em> data directly onto the fitted programs: <span class="math display">\[
Z\!F = Y \tilde F, \qquad \tilde F_{\cdot k} = \frac{F_{\cdot k}}{\lVert F_{\cdot k} \rVert_2}
\]</span></p>
<ul>
<li><span class="math inline">\(\tilde F\)</span> is <span class="math inline">\(F\)</span> with each program’s gene-weight column rescaled to unit <span class="math inline">\(L_2\)</span> norm.</li>
<li><span class="math inline">\(Z\!F\)</span> (<span class="math inline">\(n \times K\)</span>) is each patient’s projection score onto each program: a direct function of the data <span class="math inline">\(Y\)</span> and the fitted <span class="math inline">\(F\)</span>, not a latent variable with its own posterior uncertainty.</li>
<li>The rescaling is necessary: without it, <span class="math inline">\(\lVert Z\!F_{\cdot k}\rVert \sim O(\sqrt{np})\)</span> grows with the size of the data, and the survival coefficients get driven toward zero by scale alone (not because there’s no real signal).</li>
</ul>
<p><strong>Survival model (Cox proportional hazards).</strong> Patient risk is a linear combination of the projection scores: <span class="math display">\[
\eta_i = (Z\!F)_{i\cdot}\,\tilde\beta, \qquad h(t_i \mid \eta_i) = h_0(t)\exp(\eta_i)
\]</span></p>
<ul>
<li><span class="math inline">\(\eta_i\)</span> is patient <span class="math inline">\(i\)</span>’s linear predictor (log relative risk).</li>
<li><span class="math inline">\(\tilde\beta\)</span> (<span class="math inline">\(K \times 1\)</span>) is the survival coefficient vector: how prognostic each program is.</li>
<li><span class="math inline">\(h_0(t)\)</span> is an unspecified baseline hazard (standard Cox); it cancels out of the partial likelihood and is never estimated.</li>
<li><span class="math inline">\(\beta\)</span> acts on <span class="math inline">\(Z\!F\)</span> (data <span class="math inline">\(\times\)</span> fitted <span class="math inline">\(F\)</span>), not on <span class="math inline">\(L\)</span>: <span class="math inline">\(L\)</span> does not appear in the survival likelihood at all under YFB. This is the key structural difference from the LB parameterization (<span class="math inline">\(\eta = L\beta\)</span>), where <span class="math inline">\(L\)</span> carries both roles.</li>
</ul>
</section>
<section id="the-full-model-likelihood-priors-and-posteriors" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="the-full-model-likelihood-priors-and-posteriors"><span class="header-section-number">6.2.2</span> The full model: likelihood, priors, and posteriors</h3>
<p>This is the complete probabilistic model the update steps below are derived from: the two likelihoods, the priors on each latent variable, and the objective (the ELBO) that CAVI actually maximizes. Full derivation: <code>derivations/cox_on_YF/ELBO/ELBO_YF_derivation.pdf</code>.</p>
<p><strong>Priors.</strong> Each latent variable is given an Empirical Bayes prior. A family is chosen and the specific shape within that family is estimated from the data itself: <span class="math display">\[
l_{ik} \overset{\text{iid}}{\sim} g_L \in \mathcal{G}_L, \qquad
f_{jk} \overset{\text{iid}}{\sim} g_F \in \mathcal{G}_F, \qquad
\tilde\beta_k \overset{\text{iid}}{\sim} g_{\tilde\beta} \in \mathcal{G}_{\tilde\beta}
\]</span></p>
<ul>
<li><span class="math inline">\(g_L\)</span> and <span class="math inline">\(g_F\)</span>: <code>point_exponential</code>, a one-sided (non-negative) sparse family, estimated via Empirical Bayes Normal Means (EBNM). Loadings and gene weights can be zero or positive, never negative.</li>
<li><span class="math inline">\(g_{\tilde\beta}\)</span>: <code>normal</code> in the recommended configuration, a ridge-like shrinkage prior with no exact point mass at zero. A <code>point_normal</code> (spike-and-slab) alternative exists in the code but collapses <span class="math inline">\(\tilde\beta\)</span> to 0 for every <span class="math inline">\(K\)</span> under cross-validation (5/28 entry); <code>normal</code> is the prior actually used to produce every result in this notebook.</li>
<li><span class="math inline">\(\tau_j\)</span> has no prior in this model; it is fit by constrained maximum likelihood (Step 2 below), not a full variational treatment, so it contributes no KL term to the objective below.</li>
</ul>
<p><strong>Full joint likelihood.</strong> <span class="math inline">\(t = (t_1,\ldots,t_n)\)</span> are the observed survival/censoring times and <span class="math inline">\(\delta = (\delta_1,\ldots,\delta_n) \in \{0,1\}^n\)</span> the event indicators (<span class="math inline">\(\delta_i=1\)</span>: event observed; <span class="math inline">\(\delta_i=0\)</span>: censored). Together these two vectors are the survival outcome. Conditional on the latent variables, the genomics data and the survival outcome are independent: <span class="math display">\[
P(Y, t, \delta \mid L, F, \tilde\beta, \tau) =
\underbrace{P(Y \mid L, F, \tau)}_{\text{genomics}} \;\times\;
\underbrace{P(t, \delta \mid Y, F, \tilde\beta)}_{\text{survival}}
\]</span> <span class="math inline">\(P(Y \mid L, F, \tau)\)</span> is the Gaussian genomics likelihood implied by the genomics model above (product over <span class="math inline">\(i,j\)</span> of <span class="math inline">\(\mathcal{N}(y_{ij};\,\mathbf{l}_i^\top\mathbf{f}_j,\,\tau_j^{-1})\)</span>). <span class="math inline">\(P(t, \delta \mid Y, F, \tilde\beta)\)</span> is the Cox partial likelihood, a function of the linear predictor <span class="math inline">\(\eta_i = (Z\!F)_{i\cdot}\tilde\beta\)</span> from the survival model above. The survival term conditions on <span class="math inline">\(F\)</span> and the <em>observed</em> <span class="math inline">\(Y\)</span> (through <span class="math inline">\(Z\!F\)</span>), not on <span class="math inline">\(L\)</span>. This is exactly what removes <span class="math inline">\(L\)</span> from the survival side of the model under YFB.</p>
<p><strong>Posteriors.</strong> <span class="math inline">\(q(L)\)</span>, <span class="math inline">\(q(F)\)</span>, and <span class="math inline">\(q(\tilde\beta)\)</span> are the variational <strong>posteriors</strong>: CAVI’s best-fitting approximation to the true, intractable posterior <span class="math inline">\(P(L, F, \tilde\beta \mid Y, t, \delta)\)</span>, under a mean-field assumption that they factorize independently: <span class="math inline">\(q(L, F, \tilde\beta) = q(L)\,q(F)\,q(\tilde\beta)\)</span>, each further factorized coordinate-by-coordinate (<span class="math inline">\(l_{ik}\)</span>, <span class="math inline">\(f_{jk}\)</span>, <span class="math inline">\(\tilde\beta_k\)</span> each get their own independent posterior). They are <strong>not</strong> the priors <span class="math inline">\(g_L, g_F, g_{\tilde\beta}\)</span> above: the prior is the population-level shape estimated once per update from all the data; the posterior is the individual belief about one specific <span class="math inline">\(l_{ik}\)</span> (or <span class="math inline">\(f_{jk}\)</span>, <span class="math inline">\(\tilde\beta_k\)</span>) after seeing the data, given that prior. Each posterior’s mean <span class="math inline">\(\mathbb{E}_q[\cdot]\)</span> (written <span class="math inline">\(\bar l_{ik}\)</span>, <span class="math inline">\(\bar f_{jk}\)</span>, <span class="math inline">\(\bar\beta_k\)</span> below) and second moment <span class="math inline">\(\mathbb{E}_q[\cdot^2]\)</span> are both tracked, since they differ whenever there’s posterior uncertainty. This distinction matters for the <span class="math inline">\(\tau\)</span> update (Step 2) and for the error-in-variables correction in the survival term.</p>
<p><strong>The variational objective (ELBO).</strong> CAVI maximizes the Evidence Lower Bound, written <span class="math inline">\(\mathcal{L}\)</span> here (script L, not to be confused with the loading matrix <span class="math inline">\(L\)</span>): <span class="math display">\[
\mathcal{L} = \mathbb{E}_q\big[\log P(Y \mid L, F, \tau)\big]
  + \mathbb{E}_q\big[\log P(t, \delta \mid Y, F, \tilde\beta)\big]
  - \mathrm{KL}\big[q(L)\,\|\,g_L\big]
  - \mathrm{KL}\big[q(F)\,\|\,g_F\big]
  - \mathrm{KL}\big[q(\tilde\beta)\,\|\,g_{\tilde\beta}\big]
\]</span> The first two terms, <span class="math inline">\(\mathbb{E}_q[\log P(Y\mid L,F,\tau)]\)</span> and <span class="math inline">\(\mathbb{E}_q[\log P(t,\delta\mid Y,F,\tilde\beta)]\)</span>, are the two log-likelihoods from above, each averaged over the current posteriors: how well the model fits the data. Each <span class="math inline">\(\mathrm{KL}[q(\cdot)\,\|\,g] = \mathbb{E}_q\!\left[\log\frac{q(\cdot)}{g(\cdot)}\right]\)</span> is the Kullback–Leibler divergence between a posterior and its prior; it penalizes posteriors that drift too far from the prior, which is what produces shrinkage. The survival log-likelihood term is not conjugate to a Normal prior, so it’s handled by a second-order Taylor expansion around the current linear predictor <span class="math inline">\(\hat\eta\)</span> (a local Gaussian approximation) before the EBNM updates below can be applied.</p>
<p>Inference is Coordinate Ascent Variational Inference (CAVI): each coordinate posterior above is updated in turn, holding the others fixed, which turns each update into an Empirical Bayes Normal Means (EBNM) problem: solve for the prior and posterior moments given a pseudo-observation <span class="math inline">\(x\)</span> and its standard error <span class="math inline">\(s\)</span>. The exception is <span class="math inline">\(\tau\)</span>, which has a closed form.</p>
</section>
<section id="update-steps-one-outer-cavi-iteration" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="update-steps-one-outer-cavi-iteration"><span class="header-section-number">6.2.3</span> Update steps (one outer CAVI iteration)</h3>
<p>Each step below computes one of the coordinate posteriors defined above (<span class="math inline">\(q(\tilde\beta_k)\)</span>, <span class="math inline">\(q(l_{\cdot k})\)</span>, <span class="math inline">\(q(f_{\cdot k})\)</span>), given the current pseudo-data from every other coordinate.</p>
<p><strong>What <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are.</strong> Every EBNM update below follows the same pattern: collect a precision <span class="math inline">\(A\)</span> (how much information the data carries about this one coordinate; larger <span class="math inline">\(A\)</span> means a more confident estimate) and a numerator <span class="math inline">\(B\)</span> (a precision-weighted sum of the residual, or pseudo-data, relevant to that coordinate). The pair <span class="math inline">\((A,B)\)</span> converts into a pseudo-observation <span class="math inline">\(x = B/A\)</span> with standard error <span class="math inline">\(s = 1/\sqrt{A}\)</span>. That <span class="math inline">\((x,s)\)</span> pair, together with the coordinate’s prior family, is what’s actually handed to the EBNM solver, which returns the fitted prior and the posterior mean and second moment. This structure is identical for <span class="math inline">\(\beta\)</span>, <span class="math inline">\(L\)</span>, and <span class="math inline">\(F\)</span> below; only what goes into <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> changes. All three formulas were checked line-by-line against their source derivations (<code>derivations/cox_on_YF/</code>) and match exactly.</p>
<p><strong>Step 0: Working response.</strong> Recompute <span class="math inline">\(\tilde F\)</span>, <span class="math inline">\(Z\!F = Y\tilde F\)</span>, and <span class="math inline">\(\eta = Z\!F\,\tilde\beta\)</span>; run one step of the Cox Newton–Raphson (Taylor) expansion at <span class="math inline">\(\eta\)</span> to get the score <span class="math inline">\(u\)</span>, diagonal Hessian weight <span class="math inline">\(w\)</span>, and working response <span class="math inline">\(z = \eta + u/w\)</span>.</p>
<p><strong>Step 1: For each factor <span class="math inline">\(k = 1, \dots, K\)</span> (Gauss–Seidel: <span class="math inline">\(\beta_k \to l_k \to f_k\)</span>, in order):</strong></p>
<ol type="1">
<li><p><strong><span class="math inline">\(q(\beta_k)\)</span>, survival coefficient.</strong> Covariate is <span class="math inline">\(Z\!F_{\cdot k}\)</span>, observed (no posterior variance term): <span class="math display">\[
A_k = \alpha \sum_i w_i\, Z\!F_{ik}^2, \qquad
B_k = \alpha \sum_i w_i\, z^{-k}_i\, Z\!F_{ik}
\]</span> <span class="math display">\[
\left(\bar\beta_k,\ \overline{\beta_k^2}\right) \leftarrow
\mathrm{EBNM}\!\left(x=\tfrac{B_k}{A_k},\ s=\tfrac{1}{\sqrt{A_k}}\right)
\]</span> where <span class="math inline">\(z^{-k}_i = z_i - \sum_{k'\ne k} Z\!F_{ik'}\bar\beta_{k'}\)</span> is the working response with factor <span class="math inline">\(k\)</span>’s own contribution removed, and <span class="math inline">\(\alpha \in [0,1]\)</span> (default <span class="math inline">\(0.5\)</span>) is the genomics/survival mixing weight. <span class="math inline">\(\alpha\)</span> cancels in <span class="math inline">\(x_k = B_k/A_k\)</span> (the EBNM pseudo-observation is <span class="math inline">\(\alpha\)</span>-independent) but not in <span class="math inline">\(s_k = 1/\sqrt{A_k}\)</span>, so it still controls how strongly <span class="math inline">\(\beta_k\)</span> is shrunk. Prior family: <code>normal</code> (see the priors note above; <code>point_normal</code> is available but collapses to <span class="math inline">\(\beta=0\)</span> under cross-validation). <em>(Derivation: <code>derivations/cox_on_YF/qBeta/qBeta_YF_derivation.pdf</code>)</em></p></li>
<li><p><strong><span class="math inline">\(q(l_{\cdot k})\)</span>, patient loadings, pure genomics.</strong> <span class="math inline">\(L\)</span> carries no survival term under YFB: <span class="math display">\[
A_{ik} = \sum_j \tau_j\, \overline{f_{jk}^2}, \qquad
B_{ik} = \sum_j \tau_j\, R^{-k}_{ij}\, \bar f_{jk}
\]</span> <span class="math display">\[
\left(\bar l_{ik},\ \overline{l_{ik}^2}\right) \leftarrow
\mathrm{EBNM}\!\left(x=\tfrac{B_{ik}}{A_{ik}},\ s=\tfrac{1}{\sqrt{A_{ik}}}\right)
\]</span> where <span class="math inline">\(R^{-k} = Y - \bar L\bar F^\top + \bar l_{\cdot k}\bar f_{\cdot k}^\top\)</span> is the genomics residual with factor <span class="math inline">\(k\)</span> added back in. Prior family: <code>point_exponential</code> (one-sided, non-negative weights, no “depletion” side). <em>(Derivation: <code>derivations/cox_on_YF/qL_unsupervised/qL_unsupervised_derivation.pdf</code>)</em></p></li>
<li><p><strong><span class="math inline">\(q(f_{\cdot k})\)</span>, gene-program weights.</strong> Pure genomics at the default survival-mixing weight <span class="math inline">\(\alpha_F = 0\)</span> (a dual-source form exists for <span class="math inline">\(\alpha_F &gt; 0\)</span>, unused in the recommended configuration; see <code>derivations/cox_on_YF/qF_supervised/qF_supervised_derivation.pdf</code> for the general case): <span class="math display">\[
A_{jk} = \tau_j \sum_i \overline{l_{ik}^2}, \qquad
B_{jk} = \tau_j \sum_i R^{-k}_{ij}\, \bar l_{ik}
\]</span> <span class="math display">\[
\left(\bar f_{jk},\ \overline{f_{jk}^2}\right) \leftarrow
\mathrm{EBNM}\!\left(x=\tfrac{B_{jk}}{A_{jk}},\ s=\tfrac{1}{\sqrt{A_{jk}}}\right)
\]</span></p></li>
</ol>
<p><strong>Dual-source <span class="math inline">\(F\)</span> was tested, not left unused.</strong> Ran a 16-configuration experiment letting survival term inform gene-program loadings (analogous to DeSurv’s joint <span class="math inline">\(W\)</span>) and found no benefit and some harm at higher weights, so we kept the simpler genomics-only <span class="math inline">\(F\)</span>, with survival entering only through <span class="math inline">\(\beta\)</span> on <span class="math inline">\(Z\!F = Y\tilde F\)</span>. [Full method &amp; results: DECISIONS.md, 2026-08-20 entries]</p>
<p><strong>Step 2: <span class="math inline">\(q(\tau)\)</span>, closed form, no EBNM.</strong> <span class="math display">\[
\bar R^2_{ij} = \left(Y - \bar L\bar F^\top\right)^2_{ij} +
\sum_{k=1}^{K}\left[\overline{l_{ik}^2}\,\overline{f_{jk}^2} - \bar l_{ik}^2 \bar f_{jk}^2\right], \qquad
\hat\tau_j = \frac{n}{\sum_i \bar R^2_{ij}}
\]</span> The bracketed term is the posterior-variance correction; it prevents <span class="math inline">\(\tau\)</span> from being systematically overestimated by ignoring uncertainty in <span class="math inline">\(L\)</span> and <span class="math inline">\(F\)</span>.</p>
<p><strong>Step 3: Prediction.</strong> <span class="math display">\[
\widehat{\eta}_{\text{test}} = \left(Y_{\text{test}}\, \tilde F_{\text{train}}\right)\tilde\beta
\]</span></p>
<p><strong>Step 4: Sign correction.</strong> After convergence, if training concordance of <span class="math inline">\(\widehat\eta = Z\!F\,\tilde\beta\)</span> is below 0.5, flip <span class="math inline">\(\tilde\beta \to -\tilde\beta\)</span> (equivalent to <span class="math inline">\(1 - C_{\text{train}}\)</span>).</p>
<p><em>A second scalar, <span class="math inline">\(\lambda\)</span>, once multiplied the survival-side precision terms in the <span class="math inline">\(L\)</span> update separately from <span class="math inline">\(\alpha\)</span>; retired 2026-07-12 as redundant with <span class="math inline">\(\alpha\)</span> and removed from the code (DECISIONS.md).</em></p>
</section>
<section id="gene-selection" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="gene-selection"><span class="header-section-number">6.2.4</span> Gene selection</h3>
<ul>
<li>Rank genes per training cohort (TCGA-PAAD, CPTAC) by a combined mean expression + variance rank (similar to DeSurv approach), computed before normalization.</li>
<li>Keep the top 3,000 genes by that rank, per cohort.</li>
<li>Intersect the two cohorts’ gene sets: 2,064 genes survive (vs.&nbsp;2,000 under a variance-only rank).</li>
<li>Standardize per platform (<span class="math inline">\(z\)</span>-score) after intersection, before fitting. This step is required as 10 of 12 non-per-platform preprocessing variants collapsed to <span class="math inline">\(\beta = 0\)</span>.</li>
</ul>
</section>
<section id="factor-composition-k7" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="factor-composition-k7"><span class="header-section-number">6.2.5</span> Factor composition (<span class="math inline">\(K=7\)</span>)</h3>
<p><span class="math inline">\(K_{\text{eff}}=2\)</span> of the 7 fitted gene programs carry non-negligible survival weight: <span class="math inline">\(|\bar{\tilde\beta}_k| &gt; 0.001\)</span> (<code>beta_thresh</code> in <code>classify_factors()</code>, matching <code>config/globals.yml</code>’s <code>k_selection$beta_threshold</code>). The other 5 fall below that threshold and split into genomics-only (per-factor variance explained <span class="math inline">\(\text{PVE}_k &gt; 1\%\)</span>) and dead (<span class="math inline">\(\text{PVE}_k \le 1\%\)</span>, nothing retained).</p>
<p>Do we need to tune these quantities?: (1) survival coefficient threshold, (2) PVE threshold</p>
<p>Two separate decisions are involved here, and the table below only makes one of them:</p>
<ol type="1">
<li><strong>How many gene programs should the model fit (<span class="math inline">\(K\)</span>)?</strong> First proposed on 5/28 via cross-validated external C-index, but that justification is superseded this cycle (§3.1): ARD pruning within a large-<span class="math inline">\(K\)</span> fit, combined with model fit (ELBO) across candidate <span class="math inline">\(K\)</span>’s, using external C-index only as a floor to rule out a <span class="math inline">\(K\)</span> that fits training data best but generalizes worse, not as the primary selection criterion. That updated procedure re-confirms <span class="math inline">\(K=7\)</span> on its own terms. The table below takes this current, ARD/ELBO-validated <span class="math inline">\(K=7\)</span> fit as given; it does not revisit the choice of <span class="math inline">\(K\)</span> itself.</li>
<li><strong>Of those 7 fitted programs, which are actually prognostic, which are real biology with no survival link, and which are noise the model discarded?</strong> This is what the table answers, using this cycle’s new <code>classify_factors()</code> method (§3.1): 2 programs land in the first bucket (survival-active), 2 in the second (genomics-only), 3 in the third (dead).</li>
</ol>
<p>§3.1 below is where decision 1 is actually re-derived; this table only carries out decision 2 on the result.</p>
<p>Top genes within a program are ranked by <span class="math inline">\(|\bar f_{jk}|\)</span> (equivalently raw <span class="math inline">\(\bar f_{jk}\)</span>: the <code>point_exponential</code> prior gives one-sided, non-negative weights).</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Program</th>
<th>Survival-active</th>
<th>Direction<span class="math inline">\(^\dagger\)</span></th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7</td>
<td>Yes</td>
<td>Adverse</td>
<td>HR&gt;1 in 5/5 external cohorts</td>
</tr>
<tr class="even">
<td>3</td>
<td>Yes</td>
<td>Protective</td>
<td>HR&lt;1 in 5/5 external cohorts</td>
</tr>
<tr class="odd">
<td>2 of 5 remaining</td>
<td>No</td>
<td>n/a</td>
<td>Real gene-expression programs, not tied to survival; see §3.1 (cross-cohort consistency check still open, §1)</td>
</tr>
<tr class="even">
<td>3 of 5 remaining</td>
<td>No</td>
<td>n/a</td>
<td>Fully pruned by the model (see §3.1); not a “program” to characterize</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(^\dagger\)</span> Direction is read from the <em>marginal</em> survival association of each program’s projection score (Cox on <span class="math inline">\(Z\!F_{\cdot k}\)</span> alone), not the joint model’s <span class="math inline">\(\tilde\beta\)</span> sign. The two disagree for these two programs specifically (<span class="math inline">\(\hat{\tilde\beta}_7 = -0.041\)</span>, <span class="math inline">\(\hat{\tilde\beta}_3 = +0.011\)</span>), a suppression effect among correlated programs in the joint fit. The marginal convention is the one used for all adverse/protective labeling.</p>
<p><strong>Top 20 genes, by loading weight, for each survival-active program</strong>, read directly to sanity-check by eye whether the composition of each program looks coherent (full source with weights: <code>results/benchmark_sim/outputs/pathway_enrichment/K7_kept_factors_top_genes.csv</code>):</p>
<ul>
<li><strong>Program 7 (adverse):</strong> ITGA3, MET, BCAR3, FAM3C, GAPDH, ENO1, TPI1, CDCP1, PGK1, SLC16A3, LDHA, ITGB4, SLC2A1, S100A2, TGM2, B4GALT5, FSCN1, ANLN, NT5E, LAMB3</li>
<li><strong>Program 3 (protective):</strong> CAPN5, LPCAT4, MLPH, SLC45A3, TJP3, PLEKHA6, MTMR11, GALNT6, TSPAN3, CAPN8, CYP2S1, PAK1, KCNE3, FAM83E, KCNK1, ADAP1, SRC, PLA2G10, NQO1, TSPAN15</li>
</ul>
<p><strong>Reading the lists directly:</strong></p>
<ul>
<li>Program 7’s list includes several glycolysis/hypoxia genes (GAPDH, ENO1, TPI1, PGK1, LDHA, SLC16A3, SLC2A1) alongside genes reported elsewhere as basal-like PDAC markers (MET, ITGB4, LAMB3, FSCN1, S100A2). This is a pattern, not a diagnosis.</li>
<li>Program 3’s list doesn’t jump out the way Program 7’s does; it needs the formal methods rather than a read-off.</li>
<li>The 2 genomics-only programs: no gene list or biological characterization attempted yet (§3.4 flags pulling their gene lists as a follow-up).</li>
</ul>
<p><strong>Factor biology: work already done, and where it stands.</strong> Programs 3 and 7 have been characterized in some depth (July 15 cycle): gene-set enrichment via fgsea/ORA against curated PDAC gene sets, correlation with PurIST classical/basal subtype scores, overlap with DeSurv’s published gene programs, and consistency of the hazard-ratio direction across the 5 external cohorts. Five independent methods agreed: Program 7 is adverse and basal-like/squamous, Program 3 is protective and classical/differentiated-epithelial. Those results may well be sufficient as they stand.</p>
<p>The caveat is process, not evidence. This line of investigation was pursued on our own initiative rather than at the group’s direction, and the specific methods were chosen for availability rather than from a deliberate review of what the question needs. Worth a conversation to confirm the approach is the right one before the biological labels get carried into the manuscript.</p>
<p><strong>The 2 genomics-only factors are now characterized too</strong>, in a report written for this cycle. The July analysis filtered every output table to the 2 survival-active programs, so the other kept factors’ enrichment was computed and then discarded. Reporting it turns out to matter: Program 5 reads as desmoplastic stroma (7 collagens, SPARC, THBS2, FAP) and Program 6 as immune infiltrate (IKZF1, AKNA, IL10RA, HCLS1), and each of the 4 kept factors maps onto exactly one of DeSurv’s 3 published factors, with DeSurv’s combined StromalImmune factor split across our Programs 5 and 6. The 3 dead factors return zero enriched sets, which independently corroborates the genomics-only/dead split. Full detail, including the caveat above:</p>
<ul>
<li><strong>Current, 4-factor scope:</strong> <a href="../../../reports/pathway_enrichment_report_08_21_26.html"><code>pathway_enrichment_report_08_21_26</code></a></li>
<li>Superseded, 2-factor scope (Programs 3/7 findings unchanged): <a href="../../../reports/pathway_enrichment_report_07_15_26.html"><code>pathway_enrichment_report_07_15_26</code></a></li>
<li>Figures and per-program tables: <code>results/benchmark_sim/outputs/pathway_enrichment/</code></li>
</ul>
<hr>
</section>
</section>
<section id="choosing-k-cv-for-external-c-index-vs.-k-selection-from-model-elbo" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="choosing-k-cv-for-external-c-index-vs.-k-selection-from-model-elbo"><span class="header-section-number">6.3</span> Choosing <span class="math inline">\(K\)</span>: CV for external C-index vs.&nbsp;K-selection from model ELBO</h2>
<p>Two questions behind “<span class="math inline">\(K=7\)</span>, <span class="math inline">\(K_{\text{eff}}=2\)</span>”: how <span class="math inline">\(K=7\)</span> was chosen, and whether that procedure reliably finds the right number of programs. Plan: <code>docs/plans/ssbmf_factor_classification_k_selection_08_13_2026.md</code>. Exact numbers: DECISIONS.md (2026-08-19, 2026-08-20).</p>
<section id="k-selection-by-ard-pruning-and-elbo" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="k-selection-by-ard-pruning-and-elbo"><span class="header-section-number">6.3.1</span> <span class="math inline">\(K\)</span> selection by ARD pruning and ELBO</h3>
<p><strong>Method.</strong> The shrinkage prior on <span class="math inline">\(\tilde\beta\)</span> prunes unneeded factors within a single large-<span class="math inline">\(K\)</span> fit (Automatic Relevance Determination, ARD): give the model more programs than it needs and it drives the useless ones’ survival coefficients to zero on its own, without consulting the survival outcome to pick <span class="math inline">\(K\)</span>. Fit YFB on the D4 training data at <span class="math inline">\(K_{\text{init}} \in \{5,\dots,20\}\)</span>, classify every factor in each fit, and record each fit’s ELBO and external C-index.</p>
<p><strong>Three-way factor classification.</strong> The previous active/shrunk split lumped two different things together: a program can be useless for survival and still be a real, distinct gene-expression program. Splitting “shrunk” gives three categories:</p>
<ul>
<li><strong>survival-active</strong>: <span class="math inline">\(|\bar{\tilde\beta}_k| &gt; 0.001\)</span></li>
<li><strong>genomics-only</strong>: not survival-active, but <span class="math inline">\(\text{PVE}_k &gt; 1\%\)</span></li>
<li><strong>dead</strong>: neither; fully pruned</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(K_{\text{init}}\)</span></th>
<th style="text-align: right;">Survival-active</th>
<th style="text-align: right;">Genomics-only</th>
<th style="text-align: right;">Dead</th>
<th style="text-align: right;">Total kept</th>
<th style="text-align: right;">Mean external C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.596</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.597</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>7</strong></td>
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><strong>2</strong></td>
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;"><strong>4</strong></td>
<td style="text-align: right;"><strong>0.6267</strong></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.6256</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.6271</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.6279</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.6270</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.6274</td>
</tr>
</tbody>
</table>
<p><strong>Findings.</strong></p>
<ul>
<li>Survival-active count is stable at 2 for all <span class="math inline">\(K_{\text{init}} \ge 7\)</span>. Added capacity beyond that goes entirely to dead factors (3→15), which is ARD working as intended.</li>
<li><strong>The fit is stable across starting points.</strong> At every <span class="math inline">\(K \in \{5,\dots,10\}\)</span>, all 15 restarts (1 SVD initialization + 14 random) converged to the same best-ELBO solution, and random restarts never beat SVD initialization at any <span class="math inline">\(K\)</span>. This closes the factor-stability-across-seeds question left open on 8/3.</li>
<li><span class="math inline">\(K=5\)</span> has the <em>best</em> ELBO of the entire grid (−808,404 vs.&nbsp;−810,540 at <span class="math inline">\(K=7\)</span>), and per the previous point this is not a bad-initialization artifact. <span class="math inline">\(K=6\)</span>’s ELBO (−812,248) is actually <em>worse</em> than <span class="math inline">\(K=7\)</span>’s, not better, so it loses on both fit and generalization: both <span class="math inline">\(K=5\)</span> and <span class="math inline">\(K=6\)</span> generalize far worse than <span class="math inline">\(K=7\)</span> (C=0.596–0.597 vs.&nbsp;0.626–0.628 for every <span class="math inline">\(K \ge 7\)</span>), but only <span class="math inline">\(K=5\)</span> can claim a real training-fit advantage that generalization then fails to bear out. Their apparent 3rd survival-active factor does not transfer to new cohorts either way.</li>
<li>Among <span class="math inline">\(K \in \{7,\dots,10\}\)</span> (all externally indistinguishable), <span class="math inline">\(K=7\)</span> (−810,540) and <span class="math inline">\(K=9\)</span> (−810,421) are tied on ELBO: a 0.015% difference, against ~3,200–3,500-unit gaps to <span class="math inline">\(K=8\)</span>/<span class="math inline">\(K=10\)</span>.</li>
<li>ELBO gets monotonically worse past <span class="math inline">\(K \approx 10\)</span> (<span class="math inline">\(K=15\)</span>: −826,682; <span class="math inline">\(K=20\)</span>: −847,800) while finding no new structure.</li>
</ul>
<p><strong>Decision.</strong> Rank candidate <span class="math inline">\(K\)</span>’s by ELBO, but exclude any <span class="math inline">\(K\)</span> that fails on the external cohorts first. A bad external result means whatever the model is fitting internally isn’t generalizable structure, so it shouldn’t win on training-fit score alone. That excludes <span class="math inline">\(K=5\)</span>/<span class="math inline">\(K=6\)</span>. Of the remaining tie, <strong><span class="math inline">\(K=7\)</span> (2 survival-active + 2 genomics-only)</strong> is kept as the simpler model; <span class="math inline">\(K=9\)</span> (2 + 3) is recorded as a legitimate near-tied alternative. “Start as large as possible” is not supported here; <span class="math inline">\(K\)</span> in the 7–10 range performs best.</p>
</section>
<section id="simulation-check-the-procedure-over-counts-survival-active-factors" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="simulation-check-the-procedure-over-counts-survival-active-factors"><span class="header-section-number">6.3.2</span> Simulation check: the procedure over-counts survival-active factors</h3>
<p><strong>Method.</strong> Real data has no ground truth, so the procedure was tested on simulated data with a known answer: a known number of survival-linked programs shared across two simulated cohorts, plus a known number private to one cohort (real gene-expression structure, zero true survival effect by construction).</p>
<p><strong>Findings.</strong></p>
<ul>
<li>The procedure <strong>over-counted</strong> survival-active factors: 41 of 45 fits found more than the true number, none found fewer.</li>
<li>Cause: the model correctly recovers the cohort-specific programs’ gene content, then attaches a small, spurious survival coefficient to some of them. The <span class="math inline">\(|\bar{\tilde\beta}_k| &gt; 0.001\)</span> threshold only separates “exactly zero” from “not zero,” so these clear it.</li>
<li>Adding an explicit cohort-membership adjustment did not reliably fix it.</li>
<li>A relative threshold does work in simulation: with one true survival-linked program, the real one was the single largest <span class="math inline">\(|\bar{\tilde\beta}|\)</span> in all 5 seeds, with every spurious factor below 62% of that max. <code>rel_thresh = 0.65</code> separates them cleanly, and is now available as an optional setting in <code>classify_factors()</code>.</li>
</ul>
<p><strong>This threshold is not applied to the real data.</strong> Program 3 sits at ~0.28 of Program 7’s coefficient, the same low-ratio pattern the simulation flags as spurious. But Program 3 is independently confirmed real by external validation (protective HR in 5/5 held-out cohorts, §2.5). The simulated spurious factors never had that check available, because their true effect was zero by construction. Applying <code>rel_thresh</code> mechanically here would discard a program already known to be real.</p>
<p><strong>Item for discussion (misattribution of survival signal).</strong> The selection procedure can misattribute survival signal to a real-but-unrelated program when no external cohort is available to check against. This matters most for future datasets and new simulations, before their own validation exists. Options: an explicit platform/cohort adjustment, the relative-coefficient threshold above, or requiring some form of external confirmation before trusting a newly-found survival-active factor. Worth the group’s input before settling on one.</p>
</section>
<section id="significance-of-the-k5-vs.-k7-gap" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="significance-of-the-k5-vs.-k7-gap"><span class="header-section-number">6.3.3</span> Significance of the <span class="math inline">\(K=5\)</span> vs.&nbsp;<span class="math inline">\(K=7\)</span> gap</h3>
<p>C=0.596 (<span class="math inline">\(K=5\)</span>) vs.&nbsp;C=0.627 (<span class="math inline">\(K=7\)</span>). No single external cohort shows a significant difference on its own (<span class="math inline">\(n=52\)</span>–<span class="math inline">\(288\)</span> each), but pooled across all 5 (<span class="math inline">\(n=616\)</span>, 414 events) the gap is significant: <span class="math inline">\(-0.031\)</span>, 95% CI <span class="math inline">\([-0.060, -0.002]\)</span> (bootstrap). Pooled-significant but not significant cohort-by-cohort is the same pattern seen in the July two-step comparison (§1), expected for these cohort sizes and not unusual.</p>
</section>
<section id="gene-composition-of-the-kept-programs" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="gene-composition-of-the-kept-programs"><span class="header-section-number">6.3.4</span> Gene composition of the kept programs</h3>
<p>Top-20 genes by loading weight for each of <span class="math inline">\(K=7\)</span>’s 4 kept factors, using the same style of figure as the July 15 pathway-enrichment report’s gene-weight heatmap, scoped to just these 4 (the other 3, fully pruned, are omitted):</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-08-21_k7_kept_factors_heatmap.png" class="img-fluid figure-img" width="1110"></p>
<figcaption class="figure-caption">Top-20 genes per factor for the 4 kept programs. Color = raw gene weight (point-exponential prior, so all weights are non-negative); each block of genes is essentially specific to one program.</figcaption>
</figure>
</div>
</div>
</div>
<p>The structure is block-diagonal: each program’s top genes carry near-zero weight in the other 3, including the 2 genomics-only programs. Whatever biology those 2 represent is distinct from Programs 3/7 and from each other. Neither has been run through the pathway-enrichment pipeline used on Programs 3/7 (§2.5); this is an open follow-up. Full gene lists with weights: <code>results/benchmark_sim/outputs/pathway_enrichment/K7_kept_factors_top_genes.csv</code>.</p>
</section>
<section id="joint-model-vs.-two-step-baseline" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="joint-model-vs.-two-step-baseline"><span class="header-section-number">6.3.5</span> Joint model vs.&nbsp;two-step baseline</h3>
<p><strong>Question.</strong> Does YFB (joint fitting) outperform factorizing first (EBMF) and fitting Cox on the recovered factors after? Expected shape of the answer: equivalent when there is no real survival signal, with a growing joint-model advantage as signal strengthens.</p>
<p><strong>Two ways to build the baseline unfairly</strong>, both of which weaken the two-step method:</p>
<ol type="1">
<li><strong>Matching <span class="math inline">\(K\)</span> to the joint model’s answer</strong> hands the two-step method information an independent analysis would never have. But simply picking something large instead (the original <span class="math inline">\(K=20\)</span> comparison) is not automatically fairer either.</li>
<li><strong>An unregularized second-stage Cox model</strong> overfits badly with many factors and limited events. Confirmed directly: training concordance <em>rose</em> with <span class="math inline">\(K\)</span> (0.671→0.731, <span class="math inline">\(K\)</span>=7→40) while external concordance <em>fell</em> (0.623→0.578). A penalized (LASSO) Cox is also the more faithful implementation, since a two-step analysis is supposed to decide <em>which</em> factors are prognostic, not assign every factor a nonzero coefficient.</li>
</ol>
<p><strong>Final design.</strong> A large <span class="math inline">\(K\)</span> value that the two-step method wasn’t “told” (<span class="math inline">\(K\)</span>=20/<span class="math inline">\(K\)</span>=40), with regularization at stage 2 instead of plain Cox, independent of the joint model’s own results.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-08-21_yfb_vs_ebmf_lasso_k40_ci.png" class="img-fluid figure-img" width="488"></p>
<figcaption class="figure-caption">Bootstrapped difference in external C-index (YFB minus the independent two-step baseline: K=40, never informed by YFB, LASSO stage 2). The pooled interval excludes zero.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Real-data findings.</strong></p>
<ul>
<li>The joint model’s advantage is significant pooled across the 5 external cohorts: <strong>+0.026, 95% CI [0.0002, 0.0498]</strong>. Ahead in 4 of 5 cohorts individually, none significant alone at these sample sizes.</li>
<li>Joint model wins numerically in all 6 configurations tested (unregularized or LASSO <span class="math inline">\(\times\)</span> <span class="math inline">\(K\)</span>=7/20/40).</li>
<li>The gap is significant against both independent baselines (<span class="math inline">\(K\)</span>=20 and <span class="math inline">\(K\)</span>=40+LASSO) and drops to inconclusive only when the two-step method is handed YFB’s own <span class="math inline">\(K\)</span>, which is unfair in the opposite direction, not neutral.</li>
</ul>
<p>Simulation is the only way to test the zero-signal condition, since real data cannot provide it. “Signal strength” here is a multiplier (<span class="math inline">\(0, 0.25, 0.5, 1, 2\)</span>) on the true survival coefficients used to generate each simulated patient’s survival time, for the 2 simulated factors built to mirror Programs 3/7. Strength <span class="math inline">\(0\)</span> means those 2 factors have no true effect on survival at all (pure noise); strength <span class="math inline">\(1\)</span> is this project’s standard “realistic magnitude” benchmark setting (<code>config/globals.yml</code>’s <code>synthetic$b_true</code>), not a value calibrated to match the real D4 fit’s own <span class="math inline">\(\tilde\beta\)</span>, which lives on a different, <span class="math inline">\(Z\!F\)</span>-normalized scale. The other 2 simulated factors, built to mirror the genomics-only pair, always have a true survival coefficient of exactly 0, regardless of strength. This is a property of the simulated data, not anything either model estimates:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-08-21_k7_signal_sweep_comparison.png" class="img-fluid figure-img" width="520"></p>
<figcaption class="figure-caption">Held-out C-index vs.&nbsp;true survival-signal strength, in simulation, using the same two-step design (K=20, never informed by YFB, LASSO stage 2).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Simulation findings.</strong></p>
<ul>
<li>Near-equivalence at zero/low signal, as expected, since there is no survival information for the joint coupling to exploit.</li>
<li>YFB numerically ahead at the highest signal strength tested, matching the real-data direction.</li>
<li><strong>Caveat:</strong> with only 10 replicates, no single signal strength reaches significance on its own (all CIs cross zero). This is a compute limit, not a reversal. The real-data result (<span class="math inline">\(n=616\)</span>) is the decisive evidence, and the simulation corroborates it qualitatively.</li>
</ul>
<p><strong>Conclusion.</strong> The joint model’s advantage over an independent, properly built two-step baseline is real, and largest when the two-step method has to choose its own model complexity rather than being handed the answer.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/2026-08-03.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">August 3, 2026</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/2026-08-27.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">August 27, 2026</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>