<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; October 2, 2026 – SSBMF Progress Notebook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/2026-09-18.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-93f184f27b88d8509a63edf5b6815180.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/2026-10-02.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">October 2, 2026</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">SSBMF Progress Notebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this notebook</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-04-29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">April 29, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">May 7, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-05-28.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">May 28, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-07-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">July 15, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">August 3, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">August 21, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-08-27.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">August 27, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-09-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">September 4, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-09-18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">September 18, 2026</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/2026-10-02.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">October 2, 2026</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive summary</a></li>
  <li><a href="#is-the-model-correct-implementation-checks-and-simulation" id="toc-is-the-model-correct-implementation-checks-and-simulation" class="nav-link" data-scroll-target="#is-the-model-correct-implementation-checks-and-simulation"><span class="header-section-number">10.1</span> §1 — Is the model correct? Implementation checks and simulation</a></li>
  <li><a href="#what-value-does-it-add-over-the-single-modality-model" id="toc-what-value-does-it-add-over-the-single-modality-model" class="nav-link" data-scroll-target="#what-value-does-it-add-over-the-single-modality-model"><span class="header-section-number">10.2</span> §2 — What value does it add over the single-modality model?</a></li>
  <li><a href="#what-does-methylation-contribute" id="toc-what-does-methylation-contribute" class="nav-link" data-scroll-target="#what-does-methylation-contribute"><span class="header-section-number">10.3</span> §3 — What does methylation contribute?</a></li>
  <li><a href="#open-problems-and-proposed-next-steps" id="toc-open-problems-and-proposed-next-steps" class="nav-link" data-scroll-target="#open-problems-and-proposed-next-steps"><span class="header-section-number">10.4</span> §4 — Open problems and proposed next steps</a></li>
  <li><a href="#supporting-detail-the-multimodal-model" id="toc-supporting-detail-the-multimodal-model" class="nav-link" data-scroll-target="#supporting-detail-the-multimodal-model"><span class="header-section-number">10.5</span> §5 — Supporting detail: the multimodal model</a></li>
  <li><a href="#supporting-detail-single-modality-results" id="toc-supporting-detail-single-modality-results" class="nav-link" data-scroll-target="#supporting-detail-single-modality-results"><span class="header-section-number">10.6</span> §6 — Supporting detail: single-modality results</a></li>
  <li><a href="#supporting-detail-real-data-and-multimodal-results" id="toc-supporting-detail-real-data-and-multimodal-results" class="nav-link" data-scroll-target="#supporting-detail-real-data-and-multimodal-results"><span class="header-section-number">10.7</span> §7 — Supporting detail: real data and multimodal results</a></li>
  <li><a href="#supporting-detail-single-modality-z_f-and-the-α_f-question" id="toc-supporting-detail-single-modality-z_f-and-the-α_f-question" class="nav-link" data-scroll-target="#supporting-detail-single-modality-z_f-and-the-α_f-question"><span class="header-section-number">10.8</span> §8 — Supporting detail: single-modality <span class="math inline">\(Z_F\)</span> and the α_F question</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">October 2, 2026</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="executive-summary">Executive summary</h2>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>In one line:</strong> the multimodal model now works as intended in simulation. It recovers the true programs and picks the right number of them.</p>
<p>On matched TCGA → ICGC data its best result matches our established single-modality model (C = 0.685 on the same 50 donors). Across starting ranks, though, external C is typically lower (median 0.57). Methylation has not yet added predictive value.</p>
<p>The main open problem is that on real data the model does not yet choose its own number of programs.</p>
</div>
</div>
</div>
<p><strong>Three questions, three answers</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Short answer</th>
<th>Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1. Is the multimodal model implemented correctly, and can we trust it?</strong></td>
<td><strong>Yes, at the level of the code and in simulation.</strong></td>
<td>531 unit tests pass. The posterior updates match <code>ebnm</code> to <span class="math inline">\(10^{-6}\)</span>, and the compiled updates match R to <span class="math inline">\(10^{-14}\)</span>. In 486 simulated fits, the recommended configuration recovers the true programs at moderate noise, converges every time, and returns the true number of factors whatever the starting rank (§1).</td>
</tr>
<tr class="even">
<td><strong>2. What value does it add over the single-modality model?</strong></td>
<td><strong>No performance gain yet, and no new prognostic information.</strong></td>
<td>At the pre-specified starting rank it equals the established model (0.685 vs 0.685). Across starting ranks the median is 0.57. Its prognostic program is the same basal-like axis as single-modality Program 7 (§2).</td>
</tr>
<tr class="odd">
<td><strong>3. What does methylation contribute?</strong></td>
<td><strong>Interpretable structure, not prediction, so far.</strong></td>
<td>Adding methylation changes external C by +0.01. Most of the methylation signal goes to an immune program and a methylation-only program, neither prognostic. Most expression programs barely change (§3).</td>
</tr>
</tbody>
</table>
<p><strong>Open problems, for discussion</strong></p>
<ol type="1">
<li><strong>Choosing the number of programs on real data.</strong>
<ul>
<li>Pruning removed no factors at any starting rank (3–15), so the starting rank fixes the final rank, and results vary with it.</li>
<li>The reason: with 144 × 13,000 values, reconstruction outweighs survival by about <span class="math inline">\(10^4\)</span> to 1 in the evidence used for pruning.</li>
<li>Proposed next step: weight the two modalities and survival (§4).</li>
</ul></li>
<li><strong>How to get more from methylation.</strong> Screen CpGs tied to the selected genes, such as promoter CpGs, instead of the 10,000 most variable (§3).</li>
<li><strong>A low-variance prognostic program is still missed in simulation</strong> at moderate noise. This is the same question as α_F in the single-modality model (§4, §8).</li>
</ol>
<p><strong>Also this week:</strong> held-out Kaplan–Meier evidence for the single-modality model, and corrected baselines (§6). Full details are in §5–§8.</p>
<hr>
</section>
<section id="is-the-model-correct-implementation-checks-and-simulation" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="is-the-model-correct-implementation-checks-and-simulation"><span class="header-section-number">10.1</span> §1 — Is the model correct? Implementation checks and simulation</h2>
<p><strong>The configuration we recommend.</strong> The <strong>pruned fit</strong> has four parts:</p>
<ul>
<li>a per-feature intercept, so loadings describe deviation from each gene’s or CpG’s baseline;</li>
<li>signed point-Laplace loadings;</li>
<li>empirical-Bayes priors fit by marginal likelihood;</li>
<li>an evidence check (the “nullcheck”) that removes any factor the evidence lower bound (ELBO) prefers to drop.</li>
</ul>
<p><strong>What it is compared against.</strong></p>
<ul>
<li><strong>Original fit.</strong> The September implementation: no intercept, nonnegative loadings, and no pruning.</li>
<li><strong>Variance-corrected pruned fit.</strong> The same as the pruned fit, except the survival term in the ELBO subtracts a variance penalty. It gave results identical to the pruned fit in every summary, so the simpler version is kept.</li>
</ul>
<p><strong>Implementation checks.</strong></p>
<ul>
<li>The full test suite passes: 531 tests.</li>
<li>The signed-prior posteriors match <code>ebnm</code> with the prior held fixed, to <span class="math inline">\(10^{-6}\)</span>.</li>
<li>The prior fits recover known parameters.</li>
<li>The KL terms match closed forms.</li>
<li>The compiled loading sweep reproduces the R version to <span class="math inline">\(10^{-14}\)</span>; on TCGA, the loadings agree to <span class="math inline">\(5\times10^{-16}\)</span>.</li>
<li>The 35 algebra checks in <code>derivations/multimodal_YFB/verify_derivation.R</code> pass.</li>
</ul>
<p><strong>Simulation.</strong></p>
<ul>
<li><strong>Design.</strong> True <span class="math inline">\(K=3\)</span>, <span class="math inline">\(n=120\)</span>, 50 + 50 features.</li>
<li><strong>Grid.</strong> Three scenarios × two noise levels × starting ranks 3–10 and 15 × three seeds: 486 fits, none of which errored.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_pruning_K_final.png" class="img-fluid figure-img"></p>
<figcaption>Final number of factors against the starting rank (true K = 3, dashed; y = x, dotted). The original fit keeps every starting factor; the pruned fit returns about three factors at moderate noise (top row) and fewer when each true factor explains under 1% of variance (bottom row).</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Moderate noise (each true program ≈ 10% of variance)</th>
<th>Original fit</th>
<th><strong>Pruned fit</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Final <span class="math inline">\(K\)</span>, starting rank ≥ 4</td>
<td>equals the starting rank</td>
<td><strong>3.0–3.7</strong></td>
</tr>
<tr class="even">
<td>True programs recovered (<span class="math inline">\(\lvert r\rvert\ge0.7\)</span>, of 3)</td>
<td>2.74–2.78</td>
<td><strong>2.96–3.00</strong></td>
</tr>
<tr class="odd">
<td>Prognostic programs found survival-active, correct sign</td>
<td>0.89–0.93</td>
<td>0.87</td>
</tr>
<tr class="even">
<td>False survival-active factors per fit</td>
<td>0.70–0.82</td>
<td><strong>0.59–0.67</strong></td>
</tr>
<tr class="odd">
<td>Held-out C</td>
<td>0.781–0.786</td>
<td><strong>0.794–0.798</strong></td>
</tr>
<tr class="even">
<td>Converged</td>
<td>7–37%</td>
<td><strong>100%</strong></td>
</tr>
</tbody>
</table>
<p><strong>What the sweep shows.</strong></p>
<ul>
<li><strong>Moderate noise.</strong> The pruned fit recovers the truth reliably. Results are similar between the two scenarios in which every program carries variance.</li>
<li><strong>High noise</strong> (the original September design, each true factor under 1% of variance). The pruned fit’s advantage is large: held-out C is 0.79–0.81 against about 0.70, and prognostic recall is 0.52–0.67 against 0–0.30.</li>
<li><strong>Limitation.</strong> A prognostic program with little variance is missed at moderate noise by both fits.</li>
</ul>
</section>
<section id="what-value-does-it-add-over-the-single-modality-model" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="what-value-does-it-add-over-the-single-modality-model"><span class="header-section-number">10.2</span> §2 — What value does it add over the single-modality model?</h2>
<p><strong>External discrimination: parity at best.</strong> Models were trained on TCGA (144 patients) and validated on ICGC primary PDAC (50 donors, 30 deaths). All 50 donors are also in the PACA-AU RNA-seq cohort used to validate the single-modality model.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Trained on</th>
<th>ICGC primary C (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Established single-modality model</strong></td>
<td>TCGA + CPTAC</td>
<td><strong>0.685</strong> (0.576–0.785)</td>
</tr>
<tr class="even">
<td><strong>Multimodal, pruned fit, <span class="math inline">\(K_{\mathrm{init}}=7\)</span></strong></td>
<td>TCGA</td>
<td><strong>0.685</strong> (0.579–0.779)</td>
</tr>
<tr class="odd">
<td>Multimodal, pruned fit, expression only, <span class="math inline">\(K_{\mathrm{init}}=7\)</span></td>
<td>TCGA</td>
<td>0.676 (0.569–0.770)</td>
</tr>
<tr class="even">
<td>Multimodal, original fit, <span class="math inline">\(K_{\mathrm{init}}=7\)</span></td>
<td>TCGA</td>
<td>0.453 (0.319–0.599)</td>
</tr>
<tr class="odd">
<td>Two-step (factorization, then Cox), expression only</td>
<td>TCGA</td>
<td>0.525 (0.399–0.651)</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(K_{\mathrm{init}}=7\)</span> was chosen in advance to match the single-modality model.</p>
<p><strong>But the result depends on the starting rank.</strong> Pruning removed nothing on real data, so each starting rank is also the final rank:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_real_cindex_by_kinit.png" class="img-fluid figure-img"></p>
<figcaption>External C of the multimodal pruned fit on ICGC primary PDAC by starting rank, against the established single-modality model on the same donors. SA = number of survival-active programs.</figcaption>
</figure>
</div>
<ul>
<li>Across starting ranks 3–15, external C has a median of 0.57 (range 0.50–0.685).</li>
<li>At a starting rank of 5, no program is survival-active, so the risk score is constant (C = 0.5).</li>
<li>At 15, eleven of fifteen programs are survival-active, and C falls to 0.547. The extra survival associations do not hold out of sample.</li>
</ul>
<p><strong>Information.</strong> The one survival-active program at <span class="math inline">\(K_{\mathrm{init}}=7\)</span> is the basal-like vs classical axis. It is strongly prognostic in ICGC (HR 1.99 per SD, <span class="math inline">\(p=0.0003\)</span>). It corresponds to single-modality Program 7 (<span class="math inline">\(\lvert r\rvert=0.68\)</span>), which the single-modality model already finds. The multimodal model therefore reproduces the known prognostic structure but has not yet found new prognostic programs.</p>
</section>
<section id="what-does-methylation-contribute" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="what-does-methylation-contribute"><span class="header-section-number">10.3</span> §3 — What does methylation contribute?</h2>
<p><strong>To prediction: +0.01.</strong> Expression + methylation reaches 0.685 and expression alone 0.676 under the same framework, well within the uncertainty for 50 donors.</p>
<p><strong>To structure: an immune program and a methylation-only program.</strong></p>
<ul>
<li><strong>Methylation share</strong> is each program’s share of the fitted methylation signal, <span class="math inline">\(\lVert L_k\rVert^2\lVert F_{\mathrm{meth},k}\rVert^2\)</span>.</li>
<li>The <strong>methylation-only program</strong> carries 59% of the methylation signal.</li>
<li>The <strong>immune program</strong> carries 21%, with strong loadings in both genes and CpGs.</li>
<li>The <strong>exocrine program</strong> carries 9%.</li>
<li>The prognostic <strong>basal-like program</strong> carries 4.5%.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_program_modality_share.png" class="img-fluid figure-img"></p>
<figcaption>How each program divides across expression and methylation: share of each modality’s fitted signal.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_program_loadings.png" class="img-fluid figure-img"></p>
<figcaption>Top-loading genes (left) and CpGs (right) of each program, scaled to the program’s largest loading in that modality. Grey: the program carries under 2% of that modality’s signal. * survival-active.</figcaption>
</figure>
</div>
<p><strong>Most expression programs barely change when methylation is added.</strong></p>
<ul>
<li>Four of the six expression-loading programs match the expression-only fit at <span class="math inline">\(\lvert r\rvert\)</span> 0.79–0.91, including the prognostic program at 0.88.</li>
<li>The immune (0.67) and stromal (0.52) programs change more. These are where methylation adds structure.</li>
</ul>
<p><strong>Interpretation, and the next experiment.</strong></p>
<ul>
<li>At the current screening (the 10,000 most variable CpGs), methylation appears to record mainly cell composition, especially immune content, rather than tumor-intrinsic prognostic programs.</li>
<li>The natural next test is to choose CpGs for their link to the selected genes, such as promoter CpGs of those genes. That would ask more directly how methylation can add information.</li>
</ul>
</section>
<section id="open-problems-and-proposed-next-steps" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="open-problems-and-proposed-next-steps"><span class="header-section-number">10.4</span> §4 — Open problems and proposed next steps</h2>
<p><strong>1. Choosing the number of programs on real data (top priority).</strong></p>
<ul>
<li><strong>Why nothing is pruned.</strong> The nullcheck keeps a factor when removing it lowers the evidence.
<ul>
<li>On TCGA every factor’s reconstruction gain (<span class="math inline">\(10^4\)</span>–<span class="math inline">\(10^5\)</span> nats) far exceeds its KL cost.</li>
<li>Survival changes the evidence for any factor by less than 3 nats: there are 75 events against about 1.9 million reconstruction terms.</li>
<li>So the evidence supports many molecular factors, as unsupervised factorization does (flash keeps 14 on expression alone). Survival has no say in which factors are kept.</li>
</ul></li>
<li><strong>Proposal: weight the likelihood.</strong> Put weights <span class="math inline">\(w_{\mathrm{expr}}\)</span>, <span class="math inline">\(w_{\mathrm{meth}}\)</span> and <span class="math inline">\(w_{\mathrm{surv}}\)</span> on the expression, methylation and survival terms. Scaling all three together mainly changes posterior width. Two ratios matter, so tuning is a two-dimensional surface:
<ul>
<li>methylation vs expression, which balances the modalities;</li>
<li>survival vs reconstruction, which sets how much survival shapes which factors are kept.</li>
</ul></li>
<li><strong>Plan.</strong>
<ol type="1">
<li>Start from principled defaults. For example, weight each modality by <span class="math inline">\(1/p_m\)</span> so each counts equally, and put survival on the scale of one modality.</li>
<li>Map a small grid of the two ratios, scored by simulation recovery and held-out C, to show sensitivity.</li>
<li>Test whether stronger survival weight lets the model prune on real data and recover the low-variance prognostic program in simulation.</li>
</ol></li>
</ul>
<p><strong>2. Getting more information from methylation.</strong> Gene-linked CpG screening (§3). Also consider survival-aware screening, and the arcsine scale for methylation (§7).</p>
<p><strong>3. Smaller items.</strong></p>
<ul>
<li><strong>Stopping rule.</strong> Stop on the ELBO or the mean change, and run the nullcheck only on converged fits. Most real-data fits reached the 500-sweep cap with a stable risk score.</li>
<li><strong>False positives.</strong> Reduce false survival-active factors and survival-only duplicates.</li>
<li><strong>Attribution.</strong> Identify which part of the framework is responsible for its real-data gain over the original fit: the intercept, the signed loadings, or pruning.</li>
</ul>
<p><strong>4. Single-modality model.</strong> Run the α/α_F experiments (§8). The weighting proposal above is the multimodal form of the same question.</p>
<hr>
</section>
<section id="supporting-detail-the-multimodal-model" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="supporting-detail-the-multimodal-model"><span class="header-section-number">10.5</span> §5 — Supporting detail: the multimodal model</h2>
<p>The base update equations are in <code>derivations/multimodal_YFB/multimodal_YFB_derivation.pdf</code>. The intercept, signed priors, ELBO and pruning are documented in <code>DECISIONS.md</code> (2026-10-01) and <code>code/fit_multimodal_yfb.R</code>. They will be added to the derivation.</p>
<p><strong>Reconstruction.</strong> Scores are shared; each modality has its own loadings and baseline:</p>
<p><span class="math display">\[
Y_m = \mathbf 1\mu_m^\top + L F_m^\top + E_m,\qquad E_{mij}\sim N(0,\tau_{mj}^{-1}),\qquad m=1,2.
\]</span></p>
<ul>
<li><span class="math inline">\(L\ge0\)</span> is program activity per patient. <span class="math inline">\(F_m\)</span> is how far each gene or CpG moves from its baseline <span class="math inline">\(\mu_{mj}\)</span> when the program is active.</li>
<li><span class="math inline">\(\mu_m\)</span> is re-estimated every sweep.</li>
<li>Each feature has its own residual precision <span class="math inline">\(\tau_{mj}\)</span>, estimated by maximum likelihood without regularization.</li>
</ul>
<p><strong>Survival.</strong> A Cox model with <span class="math inline">\(\boldsymbol\eta = (Y_1F_1+Y_2F_2)\,\beta\)</span>. A new patient’s risk needs only their measurements and the fitted <span class="math inline">\(F\)</span> and <span class="math inline">\(\beta\)</span>. Survival enters the <span class="math inline">\(F\)</span> and <span class="math inline">\(\beta\)</span> updates, and the <span class="math inline">\(\beta\)</span> update uses <span class="math inline">\(E[Z^2]\)</span>, which corrects for the attenuation that comes from treating estimated scores as fixed. A constant shift in <span class="math inline">\(\eta\)</span> does not change the partial likelihood, so the intercept leaves survival unchanged.</p>
<p><strong>Priors.</strong> Empirical Bayes throughout.</p>
<ul>
<li>Scores: point-exponential.</li>
<li>Loadings: the family is chosen per modality (point-exponential, point-Laplace or Normal). Its parameters are fit for each modality–program pair.</li>
<li>Survival coefficients: <span class="math inline">\(\beta_k\sim N(0,s^2_{\beta_k})\)</span> with <span class="math inline">\(s^2_{\beta_k}=\max(0,x_k^2-1/A_k)\)</span>. A weak program therefore gets <span class="math inline">\(\beta_k=0\)</span> exactly.</li>
<li><strong>Survival-active</strong> means <span class="math inline">\(|E\beta_k|/\mathrm{SD}(\beta_k)\ge1.96\)</span>.</li>
</ul>
<p><strong>Fitting.</strong></p>
<ul>
<li>Coordinate-ascent variational inference, with a Cox working approximation refreshed every sweep and no tempering weights.</li>
<li>Each program is rescaled to <span class="math inline">\(\mathrm{sd}(Z_{\cdot k})=1\)</span> because its scale is not identified.</li>
<li><strong>Nullcheck.</strong> When the sweep loop ends, remove the factor whose removal does not lower <span class="math inline">\(\text{ELBO} = E_q\log p(Y\mid\cdot) + \log PL(E[\eta]) - \sum\mathrm{KL}(q\Vert g)\)</span>, then refit and repeat. The other factors are held fixed during the check; <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\tau\)</span> are re-estimated.</li>
</ul>
<p><strong>Why spare factors used to survive.</strong></p>
<ol type="1">
<li>Without an intercept, a spare factor could fit one feature exactly. Its precision then went to about <span class="math inline">\(10^{16}\)</span> (true values ≤ 2.6), which gave an unbounded likelihood gain. Adding the intercept removed this.</li>
<li>Nonnegative factors absorbed per-feature means.</li>
<li>In the September simulations each true factor explained about 0.7% of variance, below the 1% “active” cutoff. That design could not show the problem.</li>
</ol>
<p><strong>Precision models tested and not adopted.</strong></p>
<ul>
<li>One <span class="math inline">\(\tau\)</span> per modality mis-weights heteroscedastic features: no pruning, and C fell to 0.65.</li>
<li>An empirical-Bayes Gamma prior on <span class="math inline">\(\tau\)</span> learned a heavy tail, and <span class="math inline">\(\tau\)</span> still reached about <span class="math inline">\(10^{17}\)</span>.</li>
</ul>
</section>
<section id="supporting-detail-single-modality-results" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="supporting-detail-single-modality-results"><span class="header-section-number">10.6</span> §6 — Supporting detail: single-modality results</h2>
<p>The recommended single-modality fit uses <span class="math inline">\(K_{\mathrm{init}}=7\)</span> and is trained on TCGA-PAAD + CPTAC. It retains four programs:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Program</th>
<th>Role</th>
<th>Character</th>
<th>Example genes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Program 7</td>
<td>Survival-associated (adverse)</td>
<td>Basal-like / glycolytic</td>
<td><em>MET</em>, <em>ITGA3</em>, <em>ENO1</em>, <em>LDHA</em></td>
</tr>
<tr class="even">
<td>Program 3</td>
<td>Survival-associated (protective)</td>
<td>Classical / epithelial</td>
<td><em>MLPH</em>, <em>CAPN5</em>, <em>TSPAN15</em></td>
</tr>
<tr class="odd">
<td>Stromal program</td>
<td>Expression only</td>
<td>Stromal</td>
<td>collagens, <em>FAP</em>, <em>SPARC</em></td>
</tr>
<tr class="even">
<td>Immune / quiescent stroma</td>
<td>Expression only</td>
<td>Immune and quiescent stroma</td>
<td><em>IKZF1</em>, <em>IL10RA</em>, <em>SPARCL1</em></td>
</tr>
</tbody>
</table>
<p><strong>External discrimination.</strong> Mean external C over five held-out cohorts is 0.627. The two-step comparators (factorization, then Cox):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Two-step baseline</th>
<th>Mean external C</th>
<th>Single-modality model minus two-step, pooled (95% CI)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>K = 40 chosen independently, LASSO Cox stage (the fairest)</td>
<td>0.601</td>
<td><strong>+0.026 (0.0002 to 0.050)</strong>; ahead in 4 of 5 cohorts, none individually significant</td>
</tr>
<tr class="even">
<td>K = 7 matched to the model, unpenalized Cox</td>
<td>0.623</td>
<td>+0.011 (−0.013 to 0.033), not significant</td>
</tr>
<tr class="odd">
<td>K = 20, unpenalized Cox (earlier comparison)</td>
<td>0.581</td>
<td>+0.042 (0.013 to 0.071)</td>
</tr>
</tbody>
</table>
<ul>
<li>With <span class="math inline">\(\alpha_F=0\)</span> the single-modality factorization is unsupervised. The difference from the two-step pipeline therefore lies in the priors, the rank and the shrunk survival stage, not in supervised discovery of programs.</li>
<li>In practice the two approaches perform close to each other.</li>
</ul>
<p><strong>Held-out survival stratification.</strong> In every cohort the low-risk third has the best survival. The other curves do not always separate: Puleo’s low and middle thirds overlap, and in Moffitt and PACA-AU array the middle and high thirds overlap.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cohort</th>
<th>Log-rank <span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Puleo</td>
<td><span class="math inline">\(&lt;0.0001\)</span></td>
</tr>
<tr class="even">
<td>Dijk</td>
<td>0.0005</td>
</tr>
<tr class="odd">
<td>PACA-AU RNA-seq</td>
<td>0.021</td>
</tr>
<tr class="even">
<td>PACA-AU array</td>
<td>0.075</td>
</tr>
<tr class="odd">
<td>Moffitt</td>
<td>0.17</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_km_risk_external.png" class="img-fluid figure-img"></p>
<figcaption>Overall survival by within-cohort tertile of the frozen model’s risk score. No validation outcome was used to fit, orient or threshold the score.</figcaption>
</figure>
</div>
<p><strong>Both survival-associated programs keep their direction out of sample.</strong> Pooled over 616 held-out patients, with log-rank tests stratified by cohort:</p>
<ul>
<li>high Program 7 activity: worst survival (<span class="math inline">\(p&lt;0.0001\)</span>);</li>
<li>high Program 3 activity: best survival (<span class="math inline">\(p=0.004\)</span>).</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_km_programs_external.png" class="img-fluid figure-img"></p>
<figcaption>Survival by within-cohort tertile of Program 3 and Program 7 projection scores, pooled over the five held-out cohorts.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>How the reported C-indices are oriented
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>The issue.</strong> The script behind the external C table chose each risk score’s direction separately in every validation cohort, using that cohort’s outcomes. This is circular.</li>
<li><strong>The fix.</strong> The saved fit’s <span class="math inline">\(\eta\)</span> is a good-prognosis score: its training coefficients are <span class="math inline">\(\beta_7=-0.040\)</span> on the adverse program and <span class="math inline">\(\beta_3=+0.012\)</span> on the protective one. Taking risk <span class="math inline">\(=-\eta\)</span>, a single orientation that follows from those training coefficients, reproduces every reported C.</li>
<li><strong>Going forward.</strong> The script now uses fixed orientations. A model that fails in a cohort will show C &lt; 0.5.</li>
</ul>
</div>
</div>
</section>
<section id="supporting-detail-real-data-and-multimodal-results" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="supporting-detail-real-data-and-multimodal-results"><span class="header-section-number">10.7</span> §7 — Supporting detail: real data and multimodal results</h2>
<p><strong>Cohorts.</strong> <code>code/load_multiomics_data.R</code>; tests check that patient IDs agree across expression, methylation and survival.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Cohort</th>
<th>Role</th>
<th>Patients</th>
<th>Events</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TCGA-PAAD</td>
<td>training</td>
<td>144</td>
<td>75</td>
<td>6 of 150 dropped (missing or non-positive time)</td>
</tr>
<tr class="even">
<td>ICGC primary PDAC</td>
<td>validation</td>
<td>50</td>
<td>30</td>
<td>primary tumors with PDAC histology</td>
</tr>
<tr class="odd">
<td>ICGC, all donors</td>
<td>sensitivity</td>
<td>67</td>
<td>40</td>
<td>adds 10 IPMN with invasion, 4 adenosquamous, 2 acinar, 1 signet ring</td>
</tr>
</tbody>
</table>
<p><strong>Preprocessing.</strong></p>
<ul>
<li><strong>Expression.</strong> Log2; ICGC is log2(x + 1) of the provided values.</li>
<li><strong>Methylation.</strong> Beta-values on the 305,352 CpGs shared by both cohorts’ sex-chromosome filters. KNN imputation is done within each cohort; 0.07% of TCGA values were missing.</li>
<li><strong>Survival.</strong> ICGC survival agrees exactly with the PACA-AU RNA-seq table.</li>
<li><strong>Screening, on TCGA only.</strong> 3,000 genes by DeSurv’s mean + variance rank, and the 10,000 most variable CpGs.</li>
</ul>
<p><strong>Methylation scale.</strong></p>
<ul>
<li>The arcsine transform asin(2·beta − 1) halves the share of strongly skewed CpGs: 13% have |skewness| &gt; 1 on the beta scale, 6.6% after the transform.</li>
<li>Neither scale is Gaussian. Both are flatter than Normal, with median excess kurtosis about −0.7.</li>
<li>The fits use beta-values.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_methylation_skew.png" class="img-fluid figure-img"></p>
<figcaption>Per-CpG skewness on each methylation scale (TCGA, 10k screened CpGs).</figcaption>
</figure>
</div>
<p><strong>All <span class="math inline">\(K_{\mathrm{init}}=7\)</span> arms</strong> (external C, 95% CI; orientation fixed from training):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Data</th>
<th>ICGC primary</th>
<th>ICGC all</th>
<th>TCGA (training)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pruned fit</td>
<td>expression + methylation</td>
<td>0.685 (0.579–0.779)</td>
<td>0.639 (0.547–0.734)</td>
<td>0.638</td>
</tr>
<tr class="even">
<td>Pruned fit</td>
<td>expression only</td>
<td>0.676 (0.569–0.770)</td>
<td>0.653</td>
<td>0.644</td>
</tr>
<tr class="odd">
<td>Original fit</td>
<td>expression + methylation</td>
<td>0.453 (0.319–0.599)</td>
<td>0.442</td>
<td>0.597</td>
</tr>
<tr class="even">
<td>Single-modality fitter on TCGA, raw log2, 100-iteration cap (not converged)</td>
<td>expression</td>
<td>0.491 (0.364–0.633)</td>
<td>0.480 (0.369–0.581)</td>
<td>0.594</td>
</tr>
<tr class="odd">
<td>Two-step</td>
<td>expression only</td>
<td>0.525 (0.399–0.651)</td>
<td>0.527</td>
<td>0.670</td>
</tr>
<tr class="even">
<td>Two-step</td>
<td>expression + methylation</td>
<td>0.424 (0.286–0.567)</td>
<td>0.418 (0.310–0.531)</td>
<td>0.579</td>
</tr>
</tbody>
</table>
<p><strong>Starting-rank sweep.</strong> Pruned fit, expression + methylation; nothing was pruned at any rank.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(K_{\mathrm{init}}\)</span></th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
<th>15</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survival-active</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>3</td>
<td>11</td>
</tr>
<tr class="even">
<td>Converged (500 sweeps)</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="odd">
<td>ICGC primary C</td>
<td>0.557</td>
<td>0.574</td>
<td>0.500</td>
<td>0.546</td>
<td>0.685</td>
<td>0.589</td>
<td>0.572</td>
<td>0.650</td>
<td>0.547</td>
</tr>
<tr class="even">
<td>ICGC all C</td>
<td>0.499</td>
<td>0.502</td>
<td>0.500</td>
<td>0.522</td>
<td>0.639</td>
<td>0.545</td>
<td>0.547</td>
<td>0.610</td>
<td>0.531</td>
</tr>
</tbody>
</table>
<ul>
<li>Which programs are survival-active depends on the starting rank. At 10, one of the three matches Program 3 (<span class="math inline">\(\lvert r\rvert=0.68\)</span>).</li>
<li>The non-converged fits had stable risk scores: at <span class="math inline">\(K_{\mathrm{init}}=7\)</span> the largest relative change in <span class="math inline">\(\eta\)</span> was <span class="math inline">\(3.6\times10^{-4}\)</span>. The largest entry-wise change in <span class="math inline">\(LF_m^\top\)</span>, relative to its largest entry, was still about 1.5%.</li>
</ul>
<p><strong>Programs at <span class="math inline">\(K_{\mathrm{init}}=7\)</span>.</strong></p>
<ul>
<li>Hazard ratios are marginal, per within-cohort SD of each program’s projection.</li>
<li>There are 14 unadjusted tests in the table, so it is descriptive only.</li>
<li>Source: <code>results/multimodal_real/characterize_programs.R</code>, which writes <code>real_program_table_K07.csv</code>.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Program (top genes)</th>
<th>Methylation share</th>
<th>PVE</th>
<th>Survival-active</th>
<th>HR in TCGA (<span class="math inline">\(p\)</span>)</th>
<th>HR in ICGC (<span class="math inline">\(p\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td><strong>Basal-like vs classical</strong>: up <em>KRT5, KRT6A, KRT17, S100A2, MUC16</em>; down <em>CLDN18, REG4, LYZ</em></td>
<td>4.5%</td>
<td>3.6%</td>
<td><strong>yes</strong></td>
<td><strong>1.34 (0.006)</strong></td>
<td><strong>1.99 (0.0003)</strong></td>
</tr>
<tr class="even">
<td>5</td>
<td><strong>Normal vs activated stroma</strong>: up <em>ADH1B, C7, CHRDL1</em>; down <em>COL11A1, MMP11, MSLN</em></td>
<td>1.2%</td>
<td>2.6%</td>
<td>no</td>
<td>0.75 (0.04)</td>
<td>0.83 (0.46)</td>
</tr>
<tr class="odd">
<td>1</td>
<td><strong>Classical / gastric epithelial</strong>: up <em>REG4, TFF1, CLDN18, CEACAM5</em></td>
<td>4.8%</td>
<td>12.8%</td>
<td>no</td>
<td>1.07 (0.58)</td>
<td>0.79 (0.30)</td>
</tr>
<tr class="even">
<td>2</td>
<td><strong>Immune / lymphoid</strong>: up <em>CCL19, CCL21, PTPRC, LTB, SELL</em></td>
<td>20.9%</td>
<td>4.3%</td>
<td>no</td>
<td>0.85 (0.17)</td>
<td>0.87 (0.54)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Mixed: up <em>MIF, TNFRSF6B</em>; down <em>IL6ST, NCOA2</em></td>
<td>0.3%</td>
<td>16.7%</td>
<td>no</td>
<td>1.00 (0.98)</td>
<td>1.48 (0.05)</td>
</tr>
<tr class="even">
<td>6</td>
<td><strong>Exocrine / acinar</strong>: up <em>CTRB2, CPB1, PNLIP, CELA3A, PRSS1</em></td>
<td>9.3%</td>
<td>16.0%</td>
<td>no</td>
<td>0.92 (0.53)</td>
<td>1.17 (0.37)</td>
</tr>
<tr class="odd">
<td>7</td>
<td><strong>Methylation only</strong></td>
<td>58.9%</td>
<td>4.6%</td>
<td>no</td>
<td>1.11 (0.36)</td>
<td>0.87 (0.44)</td>
</tr>
</tbody>
</table>
<p><strong>Correspondence with other fits.</strong></p>
<ul>
<li>Factor 1 corresponds to single-modality Program 3 (<span class="math inline">\(\lvert r\rvert=0.79\)</span>). Here it is not survival-active.</li>
<li>Every expression-loading factor has a counterpart in Yusha’s unsupervised <code>tcga_flash_K14</code> fit (<span class="math inline">\(\lvert r\rvert\)</span> 0.60–0.87).</li>
</ul>
<p><strong>Why nothing was pruned at <span class="math inline">\(K_{\mathrm{init}}=7\)</span>.</strong> ELBO change if each factor were removed, others held fixed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Factor</th>
<th>Program</th>
<th>Reconstruction loss</th>
<th>Survival loss</th>
<th>KL saved</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>classical</td>
<td>−100,137</td>
<td>0.0</td>
<td>+22,602</td>
</tr>
<tr class="even">
<td>2</td>
<td>immune</td>
<td>−132,648</td>
<td>0.0</td>
<td>+16,504</td>
</tr>
<tr class="odd">
<td>3</td>
<td>mixed</td>
<td>−54,407</td>
<td>0.0</td>
<td>+9,351</td>
</tr>
<tr class="even">
<td>4</td>
<td>basal-like</td>
<td>−74,714</td>
<td>−2.9</td>
<td>+20,323</td>
</tr>
<tr class="odd">
<td>5</td>
<td>stroma</td>
<td>−39,226</td>
<td>−0.8</td>
<td>+14,310</td>
</tr>
<tr class="even">
<td>6</td>
<td>exocrine</td>
<td>−92,923</td>
<td>0.0</td>
<td>+18,227</td>
</tr>
<tr class="odd">
<td>7</td>
<td>methylation-only</td>
<td>−301,982</td>
<td>0.0</td>
<td>+28,895</td>
</tr>
</tbody>
</table>
<p><strong>Simulation, all scenarios.</strong> Means over starting ranks and seeds.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Noise</th>
<th>Scenario</th>
<th>Fit</th>
<th>True programs recovered</th>
<th>Prognostic recall</th>
<th>False survival-active</th>
<th>Held-out C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>moderate</td>
<td>two prognostic</td>
<td>original / <strong>pruned</strong></td>
<td>2.74 / <strong>3.00</strong></td>
<td>0.93 / 0.87</td>
<td>0.82 / <strong>0.67</strong></td>
<td>0.781 / <strong>0.798</strong></td>
</tr>
<tr class="even">
<td>moderate</td>
<td>adverse + protective</td>
<td>original / <strong>pruned</strong></td>
<td>2.78 / <strong>2.96</strong></td>
<td>0.89 / 0.87</td>
<td>0.70 / <strong>0.59</strong></td>
<td>0.786 / <strong>0.794</strong></td>
</tr>
<tr class="odd">
<td>moderate</td>
<td>low-variance prognostic</td>
<td>original / <strong>pruned</strong></td>
<td>2.00 / 1.96</td>
<td>0 / 0</td>
<td>2.22 / <strong>1.26</strong></td>
<td>0.625 / 0.625</td>
</tr>
<tr class="even">
<td>high</td>
<td>two prognostic</td>
<td>original / <strong>pruned</strong></td>
<td>0.11 / <strong>1.19</strong></td>
<td>0.06 / <strong>0.59</strong></td>
<td>2.85 / <strong>0.44</strong></td>
<td>0.695 / <strong>0.789</strong></td>
</tr>
<tr class="odd">
<td>high</td>
<td>adverse + protective</td>
<td>original / <strong>pruned</strong></td>
<td>0.59 / <strong>1.33</strong></td>
<td>0.30 / <strong>0.67</strong></td>
<td>1.41 / <strong>0.52</strong></td>
<td>0.703 / <strong>0.799</strong></td>
</tr>
<tr class="even">
<td>high</td>
<td>low-variance prognostic</td>
<td>original / <strong>pruned</strong></td>
<td>0.15 / <strong>0.93</strong></td>
<td>0 / <strong>0.52</strong></td>
<td>2.63 / <strong>1.15</strong></td>
<td>0.693 / <strong>0.805</strong></td>
</tr>
</tbody>
</table>
<ul>
<li>Pruned fits converged in every run.</li>
<li>Pruned fits were also about twice as fast (median 59 s against 119 s), because they converge.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/2026-10-02_pruning_recovery.png" class="img-fluid figure-img"></p>
<figcaption>Recovery by starting rank at moderate noise (mean over 3 seeds).</figcaption>
</figure>
</div>
</section>
<section id="supporting-detail-single-modality-z_f-and-the-α_f-question" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="supporting-detail-single-modality-z_f-and-the-α_f-question"><span class="header-section-number">10.8</span> §8 — Supporting detail: single-modality <span class="math inline">\(Z_F\)</span> and the α_F question</h2>
<p><strong>The projection score.</strong> The β derivation (<code>derivations/cox_on_YF/qBeta/qBeta_YF_derivation.pdf</code>) now defines</p>
<p><span class="math display">\[
Z_F=Y\,E[F],\qquad (z_F)_{ik}=\sum_j y_{ij}E[f_{jk}].
\]</span></p>
<ul>
<li>It is the expression profile projected onto each program’s loadings.</li>
<li><span class="math inline">\(L\)</span> appears only in the reconstruction; <span class="math inline">\(Z_F\)</span> appears only in the Cox predictor.</li>
<li>The code normalizes the loading columns, <span class="math inline">\(\hat Z_F=YE[F]D^{-1}\)</span>. This changes only the units of <span class="math inline">\(\tilde\beta\)</span>.</li>
<li>Within an iteration <span class="math inline">\(\hat Z_F\)</span> is held fixed, so there is no attenuation correction. The multimodal model has one.</li>
</ul>
<p><strong>α and α_F.</strong></p>
<ul>
<li>α = 0.5 tempers the Cox term in the β update.</li>
<li>α_F = 0 keeps survival out of the F update, so F is the same as in unsupervised factorization. The model therefore keeps high-variance programs that are also prognostic, and cannot find a low-variance prognostic program.</li>
<li>In early versions, α_F &gt; 0 started an F–L feedback loop that ended in collapse. Under the current preprocessing that no longer happens, but α_F &gt; 0 did not improve C either:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>α_F</th>
<th>0</th>
<th>0.1</th>
<th>0.3</th>
<th>0.5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean external C</td>
<td>0.6267</td>
<td>0.6268</td>
<td>0.6263</td>
<td>0.607</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Candidate</th>
<th>Mechanism</th>
<th>Changes the model?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Factor rescaling with α = α_F = 1</td>
<td>Pins each factor’s scale, as in the multimodal model</td>
<td>No</td>
</tr>
<tr class="even">
<td>2</td>
<td>Warm start from the α_F = 0 fit</td>
<td>Avoids the initialization imbalance</td>
<td>No</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Increase α_F gradually from 0 to 1</td>
<td>Optimization device; the final objective is the plain sum</td>
<td>No</td>
</tr>
<tr class="even">
<td>4</td>
<td>Reorder the updates</td>
<td>Limits each step of the coupled L–F–β system</td>
<td>No</td>
</tr>
<tr class="odd">
<td>5</td>
<td>α as a likelihood power with a stated rule</td>
<td>Tempered posterior</td>
<td>Yes (fallback)</td>
</tr>
</tbody>
</table>
<p><strong>Test, fixed in advance.</strong></p>
<ul>
<li><strong>Simulation.</strong> Plant a low-variance prognostic program. Success is recovering it (<span class="math inline">\(\lvert r\rvert\ge0.7\)</span>) and finding it survival-active more often than the α_F = 0 fit does.</li>
<li><strong>Real data.</strong> Pooled ΔC against 0.627.</li>
<li><strong>If supervision does not change F</strong>, we report that.</li>
<li><strong>Speed.</strong> With survival in F, exact updates go one feature at a time. A block update over a whole column, with the coupling bounded by a diagonal term, would restore speed.</li>
</ul>
<p><strong>Prelim.</strong> The proposal chapter draft is in <code>paper/prelim/project3-ssbmf.qmd</code> (25 pp). The independent reviews of it and of this chapter are in <code>docs/reviews/</code>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/2026-09-18.html" class="pagination-link" aria-label="September 18, 2026">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">September 18, 2026</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>